-- drop database if exists bd_hospital;
-- CREATE DATABASE bd_hospital;

-- SELECT current_database();

-- ============================================
-- MÓDULO DE PERSONAL - HOSPITAL "TODO SANO"
-- POSTGRESQL
-- ============================================

-- ===== TABLAS CATÁLOGO =====

CREATE TABLE tp_turnos (
    id_turno SERIAL PRIMARY KEY,
    nombre_turno VARCHAR(30) NOT NULL UNIQUE,
    hora_inicio TIME NOT NULL,
    hora_fin TIME NOT NULL,
    activo BOOLEAN DEFAULT TRUE
);

CREATE TABLE tp_especialidades (
    id_especialidad SERIAL PRIMARY KEY,
    nombre_especialidad VARCHAR(80) NOT NULL UNIQUE,
    tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('Medica', 'Enfermeria', 'Apoyo', 'Administrativa')),
    descripcion TEXT,
    activo BOOLEAN DEFAULT TRUE
);

CREATE TABLE tp_areas (
    id_area SERIAL PRIMARY KEY,
    nombre_area VARCHAR(80) NOT NULL UNIQUE,
    descripcion TEXT,
    activo BOOLEAN DEFAULT TRUE
);

-- ===== TABLAS PRINCIPALES =====

CREATE TABLE tp_personas (
    id_persona SERIAL PRIMARY KEY,
    ci VARCHAR(20) NOT NULL UNIQUE,
    nombres VARCHAR(100) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    fecha_nacimiento DATE NOT NULL,
    genero CHAR(1) NOT NULL CHECK (genero IN ('M', 'F', 'O')),
    telefono VARCHAR(20),
    email VARCHAR(100),
    direccion TEXT,
    foto_url VARCHAR(255),
    fecha_creacion TIMESTAMP DEFAULT NOW(),
    activo BOOLEAN DEFAULT TRUE
);

CREATE TABLE tp_pacientes (
    id_paciente SERIAL PRIMARY KEY,
    id_persona INTEGER NOT NULL UNIQUE REFERENCES tp_personas(id_persona),
    aseguradora_nombre VARCHAR(100),
    aseguradora_codigo VARCHAR(20),
    aseguradora_empresa VARCHAR(100),
    numero_poliza VARCHAR(50),
    tipo_afiliacion VARCHAR(20) NOT NULL CHECK (tipo_afiliacion IN ('Particular', 'Asegurado')),
    contacto_emergencia_nombre VARCHAR(100),
    contacto_emergencia_telefono VARCHAR(20),
    alergias_conocidas TEXT,
    observaciones TEXT,
    fecha_registro TIMESTAMP DEFAULT NOW(),
    activo BOOLEAN DEFAULT TRUE
);

CREATE TABLE tp_empleados (
    id_empleado SERIAL PRIMARY KEY,
    id_persona INTEGER NOT NULL UNIQUE REFERENCES tp_personas(id_persona),
    id_area INTEGER REFERENCES tp_areas(id_area),
    tipo_empleado VARCHAR(20) NOT NULL CHECK (tipo_empleado IN ('Medico', 'Enfermero', 'Administrativo', 'Auxiliar', 'Otro')),
    fecha_contratacion DATE NOT NULL,
    fecha_terminacion DATE,
    id_turno INTEGER NOT NULL,-- REFERENCES tp_turnos(id_turno),
    sueldo_base DECIMAL(10,2),
    activo BOOLEAN DEFAULT TRUE
);

-- ===== TABLA DE RELACIÓN PERSONAL-ESPECIALIDADES (N:M) =====

CREATE TABLE tp_empleado_especialidades (
    id_relacion SERIAL PRIMARY KEY,
    id_empleado INTEGER NOT NULL REFERENCES tp_empleados(id_empleado),
    id_especialidad INTEGER NOT NULL REFERENCES tp_especialidades(id_especialidad),
    fecha_asignacion DATE DEFAULT NOW(),
    observaciones TEXT,
    UNIQUE(id_empleado, id_especialidad)
);

-- ===== ÍNDICES ADICIONALES =====

--CREATE INDEX idx_personas_nombres_apellidos ON tp_personas (nombres, apellidos);
--CREATE INDEX idx_pacientes_aseguradora_codigo ON tp_pacientes(aseguradora_codigo);
--CREATE INDEX idx_empleados_tipo ON tp_empleados (tipo_empleado);
--CREATE INDEX idx_empleados_area ON tp_empleados (id_area);
--CREATE INDEX idx_empleados_turno ON tp_empleados (id_turno);


---***************************************************************************************
-- Seguridad
--****************************************************************************************


-- 1. Tabla de Rolees
CREATE TABLE ts_roles (
    id_rol integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_rol VARCHAR(50) NOT NULL UNIQUE,
    descripcion VARCHAR(255),
    estado_rol BOOLEAN DEFAULT TRUE
);

-- 2. Tabla de Usuarios
CREATE TABLE ts_usuarios (
    id_usuario integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_personal INT NOT NULL UNIQUE,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    estado_cuenta VARCHAR(20) DEFAULT 'ACTIVO',

    CONSTRAINT chk_estado_cuenta
        CHECK (estado_cuenta IN ('ACTIVO', 'INACTIVO', 'BLOQUEADO'))
);

-- 3. Tabla Intermedia Roles_Usuarios
CREATE TABLE ts_roles_usuarios (
    id_usuario INT NOT NULL,
    id_rol INT NOT NULL,
    fecha_asignacion DATE DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id_usuario, id_rol),

    FOREIGN KEY (id_usuario)
        REFERENCES ts_usuarios(id_usuario)
        ON DELETE CASCADE,

    FOREIGN KEY (id_rol)
        REFERENCES ts_roles(id_rol)
        ON DELETE CASCADE
);


-- ==========================================
-- MÓDULO DE FACTURACIÓN
-- ==========================================

-- 4. Tabla SC_FACTURA
CREATE TABLE td_FACTURA (
    id_factura integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente INT NOT NULL,
    id_usuario INT NOT NULL,
    nro_factura VARCHAR(50) NOT NULL UNIQUE,
    nit_cliente VARCHAR(20) NOT NULL,
    razon_social VARCHAR(150) NOT NULL,
    fecha_emision DATE DEFAULT CURRENT_TIMESTAMP,
    monto_total DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    metodo_pago VARCHAR(50) NOT NULL,

    FOREIGN KEY (id_usuario)
        REFERENCES ts_usuarios(id_usuario),

    CONSTRAINT chk_monto_total
        CHECK (monto_total >= 0),

    CONSTRAINT chk_metodo_pago
        CHECK (
            metodo_pago IN (
                'EFECTIVO',
                'TARJETA',
                'TRANSFERENCIA',
                'SEGURO'
            )
        )
);


-- 5. Tabla SC_SERVICIOS
CREATE TABLE td_SERVICIOS (
    id_servicio integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_servicio VARCHAR(50) NOT NULL UNIQUE,
    nombre_servicio VARCHAR(100) NOT NULL,
    descripcion VARCHAR(255),
    tipo_servicio VARCHAR(50),
    precio_base DECIMAL(10, 2) NOT NULL,

    CONSTRAINT chk_precio_base
        CHECK (precio_base >= 0)
);


-- 6. Tabla SC_DETALLE_FACTURA
CREATE TABLE td_DETALLE_FACTURA (
    id_detalle integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_factura INT NOT NULL,
    id_servicio INT NOT NULL,
    cantidad INT NOT NULL DEFAULT 1,
    precio_unitario DECIMAL(10, 2) NOT NULL,
    subtotal DECIMAL(10, 2) NOT NULL,

    FOREIGN KEY (id_factura)
        REFERENCES td_FACTURA(id_factura)
        ON DELETE CASCADE,

    FOREIGN KEY (id_servicio)
        REFERENCES td_SERVICIOS(id_servicio),

    CONSTRAINT chk_cantidades_detalle
        CHECK (
            cantidad > 0
            AND precio_unitario >= 0
            AND subtotal >= 0
        )
);

--**************************************************************************

-- Internaciones

--**************************************************************************
CREATE TABLE ti_tipos_habitaciones (
    id_tipo_habitacion BIGSERIAL PRIMARY KEY,
    nombre_tipo_habitacion VARCHAR(100) NOT NULL,
   descripcion_tipo_habitacion TEXT
);


-- 4. TIPOS DE INTERNACIONES

CREATE TABLE ti_tipos_internaciones(
    id_tipo_internacion BIGSERIAL PRIMARY KEY,
    nombre_tipo_internacion VARCHAR(100) NOT NULL,
    descripcion_tipo_internacion TEXT
);


-- 5. TIPOS DE ti_ALTAS


CREATE TABLE ti_tipos_altas (
    id_tipo_alta BIGSERIAL PRIMARY KEY,
    nombre_tipo_alta VARCHAR(100) NOT NULL,
    descripcion_tipo_alta TEXT
);


-- 6. ti_HABITACIONES

CREATE TABLE ti_habitaciones (
    id_habitacion BIGSERIAL PRIMARY KEY,
    id_tipo_habitacion BIGINT NOT NULL,
    numero_habitacion VARCHAR(20) NOT NULL,
    piso_habitacion INTEGER NOT NULL,
    sector_habitacion VARCHAR(100),

    CONSTRAINT fk_habitacion_tipo
        FOREIGN KEY (id_tipo_habitacion)
        REFERENCES ti_tipos_habitaciones(id_tipo_habitacion),

    CONSTRAINT uq_numero_habitacion
        UNIQUE (numero_habitacion),

    CONSTRAINT chk_piso_habitacion
        CHECK (piso_habitacion >= 0)
);


-- 7. CAMAS

CREATE TABLE ti_camas (
    id_cama BIGSERIAL PRIMARY KEY,
    id_habitacion BIGINT NOT NULL,
    estado_cama VARCHAR(30) NOT NULL DEFAULT 'DISPONIBLEti_',

    CONSTRAINT fk_cama_habitacion
        FOREIGN KEY (id_habitacion)
        REFERENCES ti_habitaciones(id_habitacion),

    CONSTRAINT chk_estado_cama
        CHECK (
            estado_cama IN (
                'DISPONIBLE',
                'OCUPADA',
                'MANTENIMIENTO',
                'INHABILITADA'
            )
        )
);


-- 8. INTERNACIONES

CREATE TABLE ti_internaciones (
    id_internacion BIGSERIAL PRIMARY KEY,
    id_medico BIGINT NOT NULL,
    id_paciente BIGINT NOT NULL,
    id_tipo_internacion BIGINT NOT NULL,
    fecha_internacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    observaciones_internacion TEXT,

    CONSTRAINT fk_internacion_doctor
        FOREIGN KEY (id_medico)
        REFERENCES tp_personas(id_persona),

    CONSTRAINT fk_internacion_paciente
        FOREIGN KEY (id_paciente)
        REFERENCES tp_personas(id_persona),

    CONSTRAINT fk_internacion_tipo
        FOREIGN KEY (id_tipo_internacion)
        REFERENCES ti_tipos_internaciones(id_tipo_internacion)
);


-- 9. ASIGNACIONES DE CAMAS

CREATE TABLE ti_asignaciones_camas (
    id_asignacion BIGSERIAL PRIMARY KEY,
    id_internacion BIGINT NOT NULL,
    id_cama BIGINT NOT NULL,
    fecha_ingreso TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_salida TIMESTAMP,
    observaciones_asignacion TEXT,

    CONSTRAINT fk_asignacion_internacion
        FOREIGN KEY (id_internacion)
        REFERENCES ti_internaciones(id_internacion),

    CONSTRAINT fk_asignacion_cama
        FOREIGN KEY (id_cama)
        REFERENCES ti_camas(id_cama),

    CONSTRAINT chk_fechas_asignacion
        CHECK (
            fecha_salida IS NULL
            OR fecha_salida >= fecha_ingreso
        )
);


-- 10. PRESCRIPCIONES

CREATE TABLE ti_prescripciones (
    id_prescripcion BIGSERIAL PRIMARY KEY,
    id_internacion BIGINT NOT NULL,

    CONSTRAINT fk_prescripcion_internacion
        FOREIGN KEY (id_internacion)
        REFERENCES ti_internaciones(id_internacion)
);


-- 11. ALTAS

CREATE TABLE ti_altas (
    id_alta BIGSERIAL PRIMARY KEY,
    id_internacion BIGINT NOT NULL,
    id_medico BIGINT NOT NULL,
    id_tipo_alta BIGINT NOT NULL,
    fecha_alta TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    observaciones_alta TEXT,

    CONSTRAINT fk_alta_internacion
        FOREIGN KEY (id_internacion)
        REFERENCES ti_internaciones(id_internacion),

    CONSTRAINT fk_alta_doctor
        FOREIGN KEY (id_medico)
        REFERENCES tp_personas(id_persona),

    CONSTRAINT fk_alta_tipo
        FOREIGN KEY (id_tipo_alta)
        REFERENCES ti_tipos_altas(id_tipo_alta),
	
    CONSTRAINT uq_alta_internacion
        UNIQUE (id_internacion)
);

---**************************************************************************
-- Farmacias
--***************************************************************************
CREATE TABLE "tf_categorias_producto" (
  "id_categoria" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) UNIQUE NOT NULL,
  "descripcion" varchar(255),
  "activo" boolean NOT NULL DEFAULT true
);

CREATE TABLE "tf_productos" (
  "id_producto" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_categoria" int NOT NULL,
  "codigo" varchar(30) UNIQUE NOT NULL,
  "nombre" varchar(150) NOT NULL,
  "tipo_producto" varchar(20) NOT NULL,
  "principio_activo" varchar(150),
  "concentracion" varchar(50),
  "presentacion" varchar(100),
  "unidad_medida" varchar(30) NOT NULL,
  "stock_minimo" decimal(12,2) NOT NULL DEFAULT 0,
  "requiere_receta" boolean NOT NULL DEFAULT false,
  "activo" boolean NOT NULL DEFAULT true
);

CREATE TABLE "tf_proveedores" (
  "id_proveedor" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "razon_social" varchar(150) NOT NULL,
  "nit" varchar(30),
  "telefono" varchar(30),
  "correo" varchar(100),
  "direccion" varchar(200),
  "activo" boolean NOT NULL DEFAULT true
);

CREATE TABLE "tf_compras" (
  "id_compra" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_proveedor" int NOT NULL,
  "id_usuario" int NOT NULL,
  "numero_documento" varchar(50),
  "fecha_compra" date NOT NULL,
  "total" decimal(12,2) NOT NULL DEFAULT 0,
  "estado" varchar(20) NOT NULL DEFAULT 'REGISTRADA'
);

CREATE TABLE "tf_detalles_compra" (
  "id_detalle_compra" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_compra" int NOT NULL,
  "id_lote" int NOT NULL,
  "cantidad" decimal(12,2) NOT NULL,
  "costo_unitario" decimal(12,2) NOT NULL,
  "subtotal" decimal(12,2) NOT NULL
);

CREATE TABLE "tf_lotes" (
  "id_lote" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_producto" int NOT NULL,
  "numero_lote" varchar(50) NOT NULL,
  "fecha_vencimiento" date,
  "stock_actual" decimal(12,2) NOT NULL DEFAULT 0,
  "estado" varchar(20) NOT NULL DEFAULT 'DISPONIBLE'
);

CREATE TABLE "tf_dispensaciones" (
  "id_dispensacion" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_receta" int NOT NULL,
  "id_factura" int NOT NULL,
  "id_usuario" int NOT NULL,
  "fecha_dispensacion" date NOT NULL,
  "estado" varchar(20) NOT NULL DEFAULT 'ENTREGADA',
  "observacion" varchar(255)
);

CREATE TABLE "tf_detalles_dispensacion" (
  "id_detalle_dispensacion" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_dispensacion" int NOT NULL,
  "id_detalle_receta" int NOT NULL,
  "id_detalle_comprobante" int NOT NULL,
  "id_lote" int NOT NULL,
  "cantidad_entregada" decimal(12,2) NOT NULL
);

CREATE TABLE "tf_consumos_internos" (
  "id_consumo" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_solicitud_insumo" int NOT NULL,
  "id_usuario" int NOT NULL,
  "fecha_consumo" date NOT NULL,
  "estado" varchar(20) NOT NULL DEFAULT 'REGISTRADO',
  "observacion" varchar(255)
);

CREATE TABLE "tf_detalles_consumo" (
  "id_detalle_consumo" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_consumo" int NOT NULL,
  "id_detalle_solicitud_consumo" int NOT NULL,
  "id_lote" int NOT NULL,
  "cantidad_entregada" decimal(12,2) NOT NULL
);

CREATE TABLE "tf_movimientos_inventario" (
  "id_movimiento" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_lote" int NOT NULL,
  "id_usuario" int NOT NULL,
  "id_detalle_compra" int,
  "id_detalle_dispensacion" int,
  "id_detalle_consumo" int,
  "tipo_movimiento" varchar(20) NOT NULL,
  "cantidad" decimal(12,2) NOT NULL,
  "fecha_movimiento" date NOT NULL,
  "motivo" varchar(200)
);

CREATE UNIQUE INDEX ON "tf_lotes" ("id_producto", "numero_lote");

CREATE INDEX ON "tf_lotes" ("fecha_vencimiento");

CREATE INDEX ON "tf_movimientos_inventario" ("fecha_movimiento");

CREATE INDEX ON "tf_movimientos_inventario" ("id_lote");

COMMENT ON TABLE "tf_categorias_producto" IS 'Tabla propia - Clasificación de medicamentos e insumos.';

COMMENT ON TABLE "tf_productos" IS 'Tabla propia - Catálogo general de medicamentos e insumos.';

COMMENT ON COLUMN "tf_productos"."tipo_producto" IS 'MEDICAMENTO o INSUMO';

COMMENT ON TABLE "tf_proveedores" IS 'Tabla propia - Proveedores de medicamentos e insumos.';

COMMENT ON TABLE "tf_compras" IS 'Tabla propia - Cabecera de compras o entradas.';

COMMENT ON COLUMN "tf_compras"."estado" IS 'REGISTRADA o ANULADA';

COMMENT ON TABLE "tf_detalles_compra" IS 'Tabla propia - Detalle de lotes recibidos en cada compra.';

COMMENT ON TABLE "tf_lotes" IS 'Tabla propia - Control de lotes, vencimientos y stock.';

COMMENT ON COLUMN "tf_lotes"."estado" IS 'DISPONIBLE, AGOTADO o VENCIDO';

COMMENT ON TABLE "tf_dispensaciones" IS 'Tabla propia - Registra la dispensación de medicamentos prescritos y autorizados.';

COMMENT ON COLUMN "tf_dispensaciones"."estado" IS 'ENTREGADA, PARCIAL o ANULADA';

COMMENT ON TABLE "tf_detalles_dispensacion" IS 'Tabla propia - Registra medicamento, autorización, lote y cantidad entregada.';

COMMENT ON TABLE "tf_consumos_internos" IS 'Tabla propia - Registra la entrega de medicamentos o insumos solicitados internamente.';

COMMENT ON COLUMN "tf_consumos_internos"."estado" IS 'REGISTRADO o ANULADO';

COMMENT ON TABLE "tf_detalles_consumo" IS 'Tabla propia - Productos y lotes entregados en consumo interno.';

COMMENT ON TABLE "tf_movimientos_inventario" IS 'Tabla propia - Kardex de entradas, salidas y ajustes.';

COMMENT ON COLUMN "tf_movimientos_inventario"."tipo_movimiento" IS 'ENTRADA, SALIDA o AJUSTE';

--COMMENT ON TABLE "usuarios" IS 'TABLA EXTERNA - Módulo de Usuarios.';

--COMMENT ON TABLE "recetas" IS 'TABLA EXTERNA - Módulo médico.';

--COMMENT ON TABLE "detalles_receta" IS 'TABLA EXTERNA - Detalle de medicamentos prescritos.';

--COMMENT ON TABLE "facturas" IS 'TABLA EXTERNA - Módulo de Cobros/Facturación.';

--COMMENT ON TABLE "detalles_comprobante" IS 'TABLA EXTERNA - Detalle de medicamentos autorizados o pagados.';

--COMMENT ON TABLE "solicitudes_insumo" IS 'TABLA EXTERNA - Solicitud de medicamentos o insumos realizada por un área hospitalaria.';

--COMMENT ON TABLE "detalles_solicitud_consumo" IS 'TABLA EXTERNA - Detalle de productos solicitados para consumo interno.';

ALTER TABLE "tf_productos" ADD FOREIGN KEY ("id_categoria") REFERENCES "tf_categorias_producto" ("id_categoria") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tf_compras" ADD FOREIGN KEY ("id_proveedor") REFERENCES "tf_proveedores" ("id_proveedor") DEFERRABLE INITIALLY IMMEDIATE;

--ALTER TABLE "tf_compras" ADD FOREIGN KEY ("id_usuario") REFERENCES "tu_usuarios" ("id_usuario") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tf_detalles_compra" ADD FOREIGN KEY ("id_compra") REFERENCES "tf_compras" ("id_compra") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tf_detalles_compra" ADD FOREIGN KEY ("id_lote") REFERENCES "tf_lotes" ("id_lote") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tf_lotes" ADD FOREIGN KEY ("id_producto") REFERENCES "tf_productos" ("id_producto") DEFERRABLE INITIALLY IMMEDIATE;

--ALTER TABLE "detalles_receta" ADD FOREIGN KEY ("id_receta") REFERENCES "recetas" ("id_receta") DEFERRABLE INITIALLY IMMEDIATE;

--ALTER TABLE "detalles_receta" ADD FOREIGN KEY ("id_producto") REFERENCES "tf_productos" ("id_producto") DEFERRABLE INITIALLY IMMEDIATE;

--ALTER TABLE "detalles_comprobante" ADD FOREIGN KEY ("id_factura") REFERENCES "facturas" ("id_factura") DEFERRABLE INITIALLY IMMEDIATE;

--ALTER TABLE "detalles_comprobante" ADD FOREIGN KEY ("id_detalle_receta") REFERENCES "detalles_receta" ("id_detalle_receta") DEFERRABLE INITIALLY IMMEDIATE;

--ALTER TABLE "tf_dispensaciones" ADD FOREIGN KEY ("id_receta") REFERENCES "recetas" ("id_receta") DEFERRABLE INITIALLY IMMEDIATE;

--ALTER TABLE "tf_dispensaciones" ADD FOREIGN KEY ("id_factura") REFERENCES "facturas" ("id_factura") DEFERRABLE INITIALLY IMMEDIATE;

--ALTER TABLE "tf_dispensaciones" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuarios" ("id_usuario") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tf_detalles_dispensacion" ADD FOREIGN KEY ("id_dispensacion") REFERENCES "tf_dispensaciones" ("id_dispensacion") DEFERRABLE INITIALLY IMMEDIATE;

--ALTER TABLE "tf_detalles_dispensacion" ADD FOREIGN KEY ("id_detalle_receta") REFERENCES "detalles_receta" ("id_detalle_receta") DEFERRABLE INITIALLY IMMEDIATE;

--ALTER TABLE "tf_detalles_dispensacion" ADD FOREIGN KEY ("id_detalle_comprobante") REFERENCES "detalles_comprobante" ("id_detalle_comprobante") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tf_detalles_dispensacion" ADD FOREIGN KEY ("id_lote") REFERENCES "tf_lotes" ("id_lote") DEFERRABLE INITIALLY IMMEDIATE;

--ALTER TABLE "detalles_solicitud_consumo" ADD FOREIGN KEY ("id_solicitud_insumo") REFERENCES "solicitudes_insumo" ("id_solicitud_insumo") DEFERRABLE INITIALLY IMMEDIATE;

--ALTER TABLE "detalles_solicitud_consumo" ADD FOREIGN KEY ("id_producto") REFERENCES "tf_productos" ("id_producto") DEFERRABLE INITIALLY IMMEDIATE;

--ALTER TABLE "tf_consumos_internos" ADD FOREIGN KEY ("id_solicitud_insumo") REFERENCES "solicitudes_insumo" ("id_solicitud_insumo") DEFERRABLE INITIALLY IMMEDIATE;

--ALTER TABLE "tf_consumos_internos" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuarios" ("id_usuario") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tf_detalles_consumo" ADD FOREIGN KEY ("id_consumo") REFERENCES "tf_consumos_internos" ("id_consumo") DEFERRABLE INITIALLY IMMEDIATE;

--ALTER TABLE "tf_detalles_consumo" ADD FOREIGN KEY ("id_detalle_solicitud_consumo") REFERENCES "detalles_solicitud_consumo" ("id_detalle_solicitud_consumo") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tf_detalles_consumo" ADD FOREIGN KEY ("id_lote") REFERENCES "tf_lotes" ("id_lote") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tf_movimientos_inventario" ADD FOREIGN KEY ("id_lote") REFERENCES "tf_lotes" ("id_lote") DEFERRABLE INITIALLY IMMEDIATE;

--ALTER TABLE "tf_movimientos_inventario" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuarios" ("id_usuario") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tf_movimientos_inventario" ADD FOREIGN KEY ("id_detalle_compra") REFERENCES "tf_detalles_compra" ("id_detalle_compra") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tf_movimientos_inventario" ADD FOREIGN KEY ("id_detalle_dispensacion") REFERENCES "tf_detalles_dispensacion" ("id_detalle_dispensacion") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tf_movimientos_inventario" ADD FOREIGN KEY ("id_detalle_consumo") REFERENCES "tf_detalles_consumo" ("id_detalle_consumo") DEFERRABLE INITIALLY IMMEDIATE;

---***************************************************************************************************************************
-- Atenciones
--**************************************************************************************************
CREATE TABLE ta_pacientes (
    id BIGSERIAL PRIMARY KEY,
    ci VARCHAR(15) UNIQUE NOT NULL,
    nombre VARCHAR(50) NOT NULL,
    apellidos VARCHAR(80) NOT NULL,
    fecha_nacimiento DATE NOT NULL,
    genero CHAR(1) CHECK (genero IN ('M', 'F', 'O')),
    tipo_seguro VARCHAR(25) NOT NULL DEFAULT 'Particular' CHECK (tipo_seguro IN ('SUS', 'Caja_Salud', 'Particular', 'Convenio')),
    telefono VARCHAR(15),
    fecha_registro TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ta_atenciones_medicas (
    id BIGSERIAL PRIMARY KEY,
    medico_id BIGINT NOT NULL,
    id_trazabilidad VARCHAR(64) NOT NULL,
    tipo_ingreso VARCHAR(20) NOT NULL CHECK (tipo_ingreso IN ('Urgencias', 'Consulta_Externa')),
    estado VARCHAR(20) NOT NULL DEFAULT 'Admisión' CHECK (estado IN ('Admisión', 'Triaje', 'Atención', 'Observación', 'Finalizado')),
    fecha_apertura TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    fecha_cierre TIMESTAMP WITH TIME ZONE,
    paciente_id BIGINT NOT NULL REFERENCES ta_pacientes(id) ON DELETE RESTRICT
);

CREATE TABLE ta_triajes (
    id BIGSERIAL PRIMARY KEY,
    enfermero_id BIGINT NOT NULL,
    presion_sistolica INT NOT NULL CHECK (presion_sistolica BETWEEN 40 AND 280),
    presion_diastolica INT NOT NULL CHECK (presion_diastolica BETWEEN 20 AND 180),
    frecuencia_cardiaca INT NOT NULL CHECK (frecuencia_cardiaca BETWEEN 30 AND 220),
    frecuencia_respiratoria INT NOT NULL CHECK (frecuencia_respiratoria BETWEEN 8 AND 60),
    saturacion_oxigeno INT NOT NULL CHECK (saturacion_oxigeno BETWEEN 30 AND 100),
    temperatura DECIMAL(4,2) NOT NULL CHECK (temperatura BETWEEN 34.0 AND 43.0),
    escala_glasgow INT NOT NULL CHECK (escala_glasgow BETWEEN 3 AND 15),
    nivel_dolor INT NOT NULL CHECK (nivel_dolor BETWEEN 0 AND 10),
    prioridad_color VARCHAR(10) NOT NULL CHECK (prioridad_color IN ('Rojo', 'Naranja', 'Amarillo', 'Verde')),
    tiempo_espera_max_min INT NOT NULL,
    fecha_evaluacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    atencion_id BIGINT UNIQUE NOT NULL REFERENCES ta_atenciones_medicas(id) ON DELETE CASCADE
);

CREATE TABLE ta_historias_clinicas_soap (
    id BIGSERIAL PRIMARY KEY,
    medico_id BIGINT NOT NULL,
    subjetivo TEXT NOT NULL,
    objetivo TEXT NOT NULL,
    analisis_cie10 VARCHAR(15) NOT NULL,
    diagnostico_descripcion TEXT NOT NULL,
    plan_tratamiento TEXT NOT NULL,
    esta_bloqueado BOOLEAN DEFAULT FALSE,
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    fecha_bloqueo TIMESTAMP WITH TIME ZONE,
    firma_digital_sello VARCHAR(64),
    atencion_id BIGINT NOT NULL REFERENCES ta_atenciones_medicas(id) ON DELETE RESTRICT
);

CREATE TABLE ta_prescripciones (
    id BIGSERIAL PRIMARY KEY,
    medicamento_id BIGINT NOT NULL,
    nombre_medicamento VARCHAR(100) NOT NULL,
    dosis_instrucciones TEXT NOT NULL,
    cantidad INT NOT NULL CHECK (cantidad > 0),
    fecha_prescripcion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    historia_soap_id BIGINT NOT NULL REFERENCES ta_historias_clinicas_soap(id) ON DELETE CASCADE
);

CREATE TABLE ta_ordenes_examenes (
    id BIGSERIAL PRIMARY KEY,
    tipo_examen VARCHAR(50) NOT NULL,
    indicaciones TEXT NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'Solicitado' CHECK (estado IN ('Solicitado', 'En_Proceso', 'Realizado', 'Cancelado')),
    fecha_solicitud TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    historia_soap_id BIGINT NOT NULL REFERENCES ta_historias_clinicas_soap(id) ON DELETE CASCADE
);

CREATE TABLE ta_procedimientos_quirurgicos (
    id BIGSERIAL PRIMARY KEY,
    nombre_procedimiento VARCHAR(150) NOT NULL,
    cirujano_id BIGINT NOT NULL,
    anestesiologo_id BIGINT NOT NULL,
    fecha_hora_inicio TIMESTAMP WITH TIME ZONE NOT NULL,
    fecha_hora_fin TIMESTAMP WITH TIME ZONE NOT NULL CHECK (fecha_hora_fin > fecha_hora_inicio),
    observaciones_quirurgicas TEXT,
    atencion_id BIGINT NOT NULL REFERENCES ta_atenciones_medicas(id) ON DELETE RESTRICT
);

CREATE TABLE ta_procedimiento_insumos (
    id BIGSERIAL PRIMARY KEY,
    insumo_id BIGINT NOT NULL,
    nombre_insumo VARCHAR(100) NOT NULL,
    cantidad_utilizada INT NOT NULL CHECK (cantidad_utilizada > 0),
    procedimiento_id BIGINT NOT NULL REFERENCES ta_procedimientos_quirurgicos(id) ON DELETE CASCADE
);

CREATE TABLE ta_procedimiento_personal (
    id BIGSERIAL PRIMARY KEY,
    personal_id BIGINT NOT NULL,
    rol VARCHAR(50) NOT NULL,
    procedimiento_id BIGINT NOT NULL REFERENCES ta_procedimientos_quirurgicos(id) ON DELETE CASCADE
);

CREATE TABLE ta_derivaciones_externas (
    id BIGSERIAL PRIMARY KEY,
    formulario_301_nro VARCHAR(20) UNIQUE NOT NULL,
    establecimiento_destino VARCHAR(100) NOT NULL,
    motivo_derivación TEXT NOT NULL,
    medico_derivador_id BIGINT NOT NULL,
    fecha_derivacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    atencion_id BIGINT NOT NULL REFERENCES ta_atenciones_medicas(id) ON DELETE RESTRICT
);

CREATE TABLE ta_cierres_atenciones (
    id BIGSERIAL PRIMARY KEY,
    destino VARCHAR(25) NOT NULL CHECK (destino IN ('Alta', 'Internación', 'Observación', 'Referencia_Externa')),
    resumen_alta TEXT NOT NULL,
    medico_cierre_id BIGINT NOT NULL,
    fecha_cierre TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    atencion_id BIGINT UNIQUE NOT NULL REFERENCES ta_atenciones_medicas(id) ON DELETE RESTRICT
);

CREATE TABLE ta_cola_mensajes (
    id BIGSERIAL PRIMARY KEY,
    servicio_destino VARCHAR(30) NOT NULL CHECK (servicio_destino IN ('G1_FACTURACION', 'G4_FARMACIA')),
    endpoint VARCHAR(100) NOT NULL,
    payload_json JSONB NOT NULL,
    id_trazabilidad VARCHAR(64) NOT NULL,
    estado_envio VARCHAR(15) NOT NULL DEFAULT 'Pendiente' CHECK (estado_envio IN ('Pendiente', 'Enviado', 'Fallido')),
    intentos INT DEFAULT 0,
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ultimo_intento TIMESTAMP WITH TIME ZONE
);

CREATE OR REPLACE FUNCTION fn_bloquear_soap_finalizado()
RETURNS TRIGGER AS $$
BEGIN
    IF OLD.esta_bloqueado = TRUE THEN
        RAISE EXCEPTION 'Excepción Médico-Legal: No se permite la alteración de un expediente clínico firmado y cerrado (R.M. 0090/2008).';
    END IF;

    IF NEW.esta_bloqueado = TRUE AND (OLD.esta_bloqueado = FALSE OR OLD.esta_bloqueado IS NULL) THEN
        NEW.fecha_bloqueo := CURRENT_TIMESTAMP;
        NEW.firma_digital_sello := md5(NEW.id::text || NEW.analisis_cie10 || NEW.medico_id::text || CURRENT_TIMESTAMP::text);
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tga_bloquear_soap_finalizado
BEFORE UPDATE OR DELETE ON ta_historias_clinicas_soap
FOR EACH ROW
EXECUTE FUNCTION fn_bloquear_soap_finalizado();

CREATE OR REPLACE PROCEDURE pa_registrar_triaje(
    p_atencion_id BIGINT,
    p_enfermero_id BIGINT,
    p_sistolica INT,
    p_diastolica INT,
    p_fc INT,
    p_fr INT,
    p_so2 INT,
    p_temp DECIMAL(4,2),
    p_glasgow INT,
    p_dolor INT,
    p_prioridad VARCHAR(10),
    p_espera INT
)
AS $$
BEGIN
    INSERT INTO ta_triajes (
        atencion_id, enfermero_id, presion_sistolica, presion_diastolica,
        frecuencia_cardiaca, frecuencia_respiratoria, saturacion_oxigeno,
        temperatura, escala_glasgow, nivel_dolor, prioridad_color, tiempo_espera_max_min
    ) VALUES (
        p_atencion_id, p_enfermero_id, p_sistolica, p_diastolica,
        p_fc, p_fr, p_so2, p_temp, p_glasgow, p_dolor, p_prioridad, p_espera
    );

    UPDATE ta_atenciones_medicas
    SET estado = 'Triaje'
    WHERE id = p_atencion_id;

    COMMIT;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE PROCEDURE pa_registrar_nota_soap(
    p_atencion_id BIGINT,
    p_medico_id BIGINT,
    p_subjetivo TEXT,
    p_objetivo TEXT,
    p_analisis_cie10 VARCHAR(15),
    p_diagnostico TEXT,
    p_plan TEXT,
    p_bloquear BOOLEAN
)
AS $$
BEGIN
    INSERT INTO ta_historias_clinicas_soap (
        atencion_id, medico_id, subjetivo, objetivo,
        analisis_cie10, diagnostico_descripcion, plan_tratamiento, esta_bloqueado
    ) VALUES (
        p_atencion_id, p_medico_id, p_subjetivo, p_objetivo,
        p_analisis_cie10, p_diagnostico, p_plan, p_bloquear
    );

    UPDATE ta_atenciones_medicas
    SET estado = 'Atención'
    WHERE id = p_atencion_id AND estado != 'Finalizado';

    COMMIT;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE PROCEDURE pa_registrar_prescripcion(
    p_historia_soap_id BIGINT,
    p_medicamento_id BIGINT,
    p_nombre_medicamento VARCHAR(100),
    p_dosis TEXT,
    p_cantidad INT
)
AS $$
BEGIN
    INSERT INTO ta_prescripciones (
        historia_soap_id, medicamento_id, nombre_medicamento, dosis_instrucciones, cantidad
    ) VALUES (
        p_historia_soap_id, p_medicamento_id, p_nombre_medicamento, p_dosis, p_cantidad
    );

    COMMIT;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE PROCEDURE pa_registrar_orden_examen(
    p_historia_soap_id BIGINT,
    p_tipo_examen VARCHAR(50),
    p_indicaciones TEXT
)
AS $$
BEGIN
    INSERT INTO ta_ordenes_examenes (
        historia_soap_id, tipo_examen, indicaciones
    ) VALUES (
        p_historia_soap_id, p_tipo_examen, p_indicaciones
    );

    COMMIT;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE PROCEDURE pa_registrar_procedimiento_quirurgico(
    p_atencion_id BIGINT,
    p_nombre VARCHAR(150),
    p_cirujano_id BIGINT,
    p_anestesiologo_id BIGINT,
    p_inicio TIMESTAMP WITH TIME ZONE,
    p_fin TIMESTAMP WITH TIME ZONE,
    p_obs TEXT
)
AS $$
BEGIN
    INSERT INTO ta_procedimientos_quirurgicos (
        atencion_id, nombre_procedimiento, cirujano_id, anestesiologo_id,
        fecha_hora_inicio, fecha_hora_fin, observaciones_quirurgicas
    ) VALUES (
        p_atencion_id, p_nombre, p_cirujano_id, p_anestesiologo_id,
        p_inicio, p_fin, p_obs
    );

    UPDATE ta_atenciones_medicas
    SET estado = 'Observación'
    WHERE id = p_atencion_id;

    COMMIT;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE PROCEDURE pa_registrar_derivacion(
    p_atencion_id BIGINT,
    p_form_301 VARCHAR(20),
    p_destino VARCHAR(100),
    p_motivo TEXT,
    p_medico_id BIGINT
)
AS $$
BEGIN
    INSERT INTO ta_derivaciones_externas (
        atencion_id, formulario_301_nro, establecimiento_destino,
        motivo_derivación, medico_derivador_id
    ) VALUES (
        p_atencion_id, p_form_301, p_destino, p_motivo, p_medico_id
    );

    UPDATE ta_atenciones_medicas
    SET estado = 'Finalizado', fecha_cierre = CURRENT_TIMESTAMP
    WHERE id = p_atencion_id;

    COMMIT;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE PROCEDURE pa_finalizar_atencion_medica(
    p_atencion_id BIGINT,
    p_destino VARCHAR(25),
    p_medico_cierre_id BIGINT,
    p_resumen_alta TEXT
)
AS $$
DECLARE
    v_paciente_id BIGINT;
    v_trazabilidad_id VARCHAR(64);
    v_payload_g1 JSONB;
    v_payload_g4 JSONB;
    v_historia_soap_id BIGINT;
BEGIN
    SELECT paciente_id, id_trazabilidad INTO v_paciente_id, v_trazabilidad_id
    FROM ta_atenciones_medicas WHERE id = p_atencion_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Error: El ID de atención médica proporcionado no existe en el sistema.';
    END IF;

    SELECT id INTO v_historia_soap_id FROM ta_historias_clinicas_soap
    WHERE atencion_id = p_atencion_id AND esta_bloqueado = TRUE
    ORDER BY fecha_creacion DESC LIMIT 1;

    INSERT INTO ta_cierres_atenciones (atencion_id, destino, resumen_alta, medico_cierre_id)
    VALUES (p_atencion_id, p_destino, p_resumen_alta, p_medico_cierre_id);

    UPDATE ta_atenciones_medicas
    SET estado = 'Finalizado', fecha_cierre = CURRENT_TIMESTAMP
    WHERE id = p_atencion_id;

    SELECT jsonb_build_object(
        'id_trazabilidad', v_trazabilidad_id,
        'paciente_id', v_paciente_id,
        'atencion_id', p_atencion_id,
        'medico_cierre_id', p_medico_cierre_id,
        'servicios_prestados', (
            SELECT jsonb_agg(jsonb_build_object('item', nombre_medicamento, 'cantidad', cantidad))
            FROM ta_prescripciones WHERE historia_soap_id = v_historia_soap_id
        )
    ) INTO v_payload_g1;

    INSERT INTO ta_cola_mensajes (servicio_destino, endpoint, payload_json, id_trazabilidad)
    VALUES ('G1_FACTURACION', '/api/v1/facturas/recibir-cargo', v_payload_g1, v_trazabilidad_id);

    SELECT jsonb_build_object(
        'id_trazabilidad', v_trazabilidad_id,
        'receta_id', v_historia_soap_id,
        'medicamentos', (
            SELECT jsonb_agg(jsonb_build_object('medicamento_id', medicamento_id, 'cantidad', cantidad))
            FROM ta_prescripciones WHERE historia_soap_id = v_historia_soap_id
        )
    ) INTO v_payload_g4;

    INSERT INTO ta_cola_mensajes (servicio_destino, endpoint, payload_json, id_trazabilidad)
    VALUES ('G4_FARMACIA', '/api/v1/inventario/descontar', v_payload_g4, v_trazabilidad_id);

    COMMIT;
END;
$$ LANGUAGE plpgsql;

--------***************************************************************************
-- Citas
--*************************************************************************************

-- =====================================================================
-- DISENO DE BASE DE DATOS: Hospital_Prototipo_Citas
-- Sistema de gestion de citas medicas (PostgreSQL 18 / PostgREST)
-- ---------------------------------------------------------------------
-- Contenido:
--   1. Tipos ENUM
--   2. Tablas maestras      (tp_tturno, tp_tareas, tc_tservicios, tp_tespecialidad,
--                            tc_taseguradora)
--   3. Personas y empleados (tp_tpersonas, tp_templeados,
--                            tp_templeado_especialidades)
--   4. Operacion            (tp_tasegurado, tc_thorario, tc_tficha)
--   5. Indices
--   6. Funciones
--   7. Triggers
--   8. Vista
-- =====================================================================


-- =====================================================================
-- 1. TIPOS ENUM
-- =====================================================================

CREATE TYPE tipo_especialidad_enum AS ENUM (
    'medica',
    'enfermeria',
    'apoyo',
    'administrativa'
);

CREATE TYPE tipo_empleado_enum AS ENUM (
    'medico',
    'enfermero',
    'administrativo',
    'auxiliar',
    'otro'
);


-- =====================================================================
-- 2. TABLAS MAESTRAS
-- =====================================================================
/*
-- Turnos laborales / de atencion ---------------------------------------
CREATE TABLE tp_tturno (
    id_turno         integer NOT NULL PRIMARY KEY,
    descripcion      varchar(15)  NOT NULL,
    hora_inicio      time WITHOUT TIME ZONE NOT NULL,
    hora_fin         time WITHOUT TIME ZONE NOT NULL,
    cruza_medianoche boolean NOT NULL DEFAULT false,
    activo           boolean NOT NULL DEFAULT true
);

-- Areas organizacionales ------------------------------------------------
CREATE TABLE tp_areas (
    id_area     integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre_area varchar(60) NOT NULL UNIQUE,
    descripcion text        NOT NULL DEFAULT '',
    activo      boolean     NOT NULL DEFAULT true
);
*/
-- Servicios hospitalarios (se asignan en cada cita) ---------------------
CREATE TABLE tc_servicios (
    id_servicio     integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre_servicio varchar(60) NOT NULL UNIQUE,
    descripcion     text        NOT NULL DEFAULT '',
    activo          boolean     NOT NULL DEFAULT true
);
/*
-- Especialidades medicas -------------------------------------------------
CREATE TABLE tp_tespecialidad (
    id_especialidad    integer NOT NULL PRIMARY KEY,
    nombre_especialidad varchar(60) NOT NULL,
    tipo               tipo_especialidad_enum NOT NULL DEFAULT 'medica',
    descripcion        text   NOT NULL DEFAULT '',
    activo             boolean NOT NULL DEFAULT true
);
*/
-- Aseguradoras ------------------------------------------------------------
CREATE TABLE tc_aseguradora (
    id_aseguradora integer NOT NULL PRIMARY KEY,
    nombre         varchar(80)  NOT NULL,
    nit            varchar(20)  NOT NULL DEFAULT '',
    telefono       varchar(20)  NOT NULL DEFAULT '',
    direccion      varchar(150) NOT NULL DEFAULT '',
    activo         boolean      NOT NULL DEFAULT true
);


-- =====================================================================
-- 3. PERSONAS Y EMPLEADOS
-- =====================================================================
/*
-- Persona base (empleados; extensible a pacientes) ----------------------
CREATE TABLE tp_tpersonas (
    id_persona       integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ci               varchar(20) NOT NULL UNIQUE,
    nombre           varchar(80) NOT NULL,
    apellidos        varchar(80) NOT NULL DEFAULT '',
    fecha_nacimiento date,
    genero           char(1) CHECK (genero IS NULL OR genero IN ('F','M')),
    telefono         varchar(20)  NOT NULL DEFAULT '',
    email            varchar(100) NOT NULL DEFAULT '',
    direccion        text,
    foto_url         varchar(255),
    fecha_creacion   timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    activo           boolean   NOT NULL DEFAULT true
);

-- Empleados del hospital (medicos, enfermeros, administrativos...) ------
CREATE TABLE tp_templeados (
    id_empleado        integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_persona         integer NOT NULL UNIQUE REFERENCES tp_tpersonas(id_persona),
    id_area            integer REFERENCES tp_tareas(id_area),
    tipo_empleado      tipo_empleado_enum NOT NULL,
    fecha_contratacion date,
    fecha_terminacion  date,
    id_turno           integer REFERENCES tp_tturno(id_turno),
    sueldo_base        numeric(10,2) NOT NULL DEFAULT 0,
    -- Matricula profesional (aplica a medicos)
    nmp                varchar(20) NOT NULL DEFAULT '',
    activo             boolean NOT NULL DEFAULT true,
    CONSTRAINT tp_templeados_sueldo_check CHECK (sueldo_base >= 0),
    CONSTRAINT tp_templeados_fechas_check
        CHECK (fecha_terminacion IS NULL OR fecha_contratacion IS NULL
               OR fecha_terminacion >= fecha_contratacion)
);

-- Especialidades por empleado (relacion N:M) ------------------------------
CREATE TABLE tp_templeado_especialidades (
    id_relacion      integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_empleado      integer NOT NULL REFERENCES tp_templeados(id_empleado) ON DELETE CASCADE,
    id_especialidad  integer NOT NULL REFERENCES tp_tespecialidad(id_especialidad),
    fecha_asignacion date NOT NULL DEFAULT CURRENT_DATE,
    observaciones    text NOT NULL DEFAULT '',
    CONSTRAINT tp_templeado_especialidades_unica UNIQUE (id_empleado, id_especialidad)
);
*/

-- =====================================================================
-- 4. OPERACION
-- =====================================================================

-- Pacientes asegurados ----------------------------------------------------
CREATE TABLE tp_asegurado (
    ci              varchar(15) NOT NULL PRIMARY KEY,
    id_aseguradora  integer NOT NULL REFERENCES tc_aseguradora(id_aseguradora),
    nombre          varchar(50) NOT NULL,
    paterno         varchar(30) NOT NULL DEFAULT '',
    materno         varchar(30) NOT NULL DEFAULT '',
    nro_poliza      varchar(30) NOT NULL DEFAULT '',
    fech_nac        date,
    fech_afiliacion date    NOT NULL DEFAULT CURRENT_DATE,
    estado          boolean NOT NULL DEFAULT true
);

-- Horarios de atencion por empleado medico --------------------------------
CREATE TABLE tc_horario (
    id_horario  integer NOT NULL PRIMARY KEY,
    id_empleado integer NOT NULL REFERENCES tp_empleados(id_empleado),
    dia_semana  smallint NOT NULL,
    id_turno    integer  NOT NULL REFERENCES tp_turnos(id_turno),
    hora_inicio time WITHOUT TIME ZONE NOT NULL,
    hora_fin    time WITHOUT TIME ZONE NOT NULL,
    nro_fichas  integer NOT NULL DEFAULT 5,
    activo      boolean NOT NULL DEFAULT true,
    CONSTRAINT tc_horario_dia_semana_check  CHECK (dia_semana BETWEEN 1 AND 7),
    CONSTRAINT tc_horario_nro_fichas_check  CHECK (nro_fichas >= 0)
);

-- Fichas de cita -------------------------------------------------------------
CREATE TABLE tc_ficha (
    id_ficha        integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nro_ficha       integer NOT NULL,
    id_persona      integer NOT NULL,
    ci_paciente     varchar(15) NOT NULL,
    tipo_paciente   char(1)     NOT NULL DEFAULT 'P',
    id_asegurado    varchar(15) REFERENCES tp_asegurado(ci),
    id_medico       integer NOT NULL REFERENCES tp_empleados(id_empleado),
    id_especialidad integer NOT NULL REFERENCES tp_especialidades(id_especialidad),
    id_horario      integer NOT NULL REFERENCES tc_horario(id_horario),
    id_servicio     integer REFERENCES tc_servicios(id_servicio),
    fech_cita       date NOT NULL,
    hora_cita       time WITHOUT TIME ZONE NOT NULL,
    -- Estado: R=Registrada C=Confirmada A=Atendida N=No asistio X=Cancelada
    estado          char(1) NOT NULL DEFAULT 'R',
    observacion     varchar(200) NOT NULL DEFAULT '',
    fech_reg        timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    usuario_reg     varchar(15) NOT NULL DEFAULT '',
    CONSTRAINT tc_ficha_tipo_paciente_check
        CHECK (tipo_paciente IN ('A','P')),   -- A=Asegurado P=Particular
    CONSTRAINT tc_ficha_estado_check
        CHECK (estado IN ('R','C','A','N','X'))
);


-- =====================================================================
-- 5. INDICES
-- =====================================================================

--CREATE INDEX idx_temp_esp_especialidad ON tp_templeado_especialidades(id_especialidad);
CREATE INDEX idx_horario_id_empleado  ON tc_horario(id_empleado);
CREATE INDEX idx_ficha_fecha           ON tc_ficha(fech_cita);
CREATE INDEX idx_ficha_horario         ON tc_ficha(id_horario, fech_cita);


-- =====================================================================
-- 6. FUNCIONES
-- =====================================================================

-- Valida que las horas del horario caigan dentro del turno asignado -----
CREATE OR REPLACE FUNCTION trg_valida_horario()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
DECLARE
    v_inicio TIME;
    v_fin    TIME;
    v_cruza  BOOLEAN;
BEGIN
    SELECT t.hora_inicio, t.hora_fin, t.cruza_medianoche
      INTO v_inicio, v_fin, v_cruza
      FROM tp_turno t
     WHERE t.id_turno = NEW.id_turno;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Turno inexistente: %', NEW.id_turno;
    END IF;

    IF NOT v_cruza THEN
        -- Turno normal (Manana / Tarde): las horas deben caer dentro de la franja
        IF NEW.hora_inicio < v_inicio OR NEW.hora_fin > v_fin THEN
            RAISE EXCEPTION 'El horario %-% no corresponde al turno % (% - %)',
                NEW.hora_inicio, NEW.hora_fin, v_inicio, v_inicio, v_fin;
        END IF;
    ELSE
        -- Turno que cruza la medianoche (Noche)
        IF NEW.hora_inicio <= NEW.hora_fin THEN
            -- no cruza medianoche: solo franja 19:00-24:00 o 00:00-07:00
            IF NEW.hora_fin > v_fin AND NEW.hora_inicio < v_inicio THEN
                RAISE EXCEPTION 'El horario %-% cae en horario de descanso',
                    NEW.hora_inicio, NEW.hora_fin;
            END IF;
        ELSE
            -- cruza medianoche
            IF NEW.hora_inicio < v_inicio OR NEW.hora_fin > v_fin THEN
                RAISE EXCEPTION 'El horario %-% excede el turno nocturno (% - %)',
                    NEW.hora_inicio, NEW.hora_fin, v_inicio, v_fin;
            END IF;
        END IF;
    END IF;

    RETURN NEW;
END;
$function$;

-- Solo empleados de tipo medico pueden tener horarios o citas -----------
CREATE OR REPLACE FUNCTION f_valida_empleado_medico()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    v_id   integer;
    v_tipo tipo_empleado_enum;
BEGIN
    v_id := COALESCE((to_jsonb(NEW) ->> 'id_empleado')::integer,
                     (to_jsonb(NEW) ->> 'id_medico')::integer);
    IF v_id IS NULL THEN RETURN NEW; END IF;
    SELECT tipo_empleado INTO v_tipo FROM tp_empleados WHERE id_empleado = v_id;
    IF v_tipo IS DISTINCT FROM 'medico' THEN
        RAISE EXCEPTION 'El empleado % no puede atender citas/horarios (tipo=%)', v_id, v_tipo;
    END IF;
    RETURN NEW;
END $$;

-- Horarios con fichas disponibles para una especialidad y fecha ----------
CREATE OR REPLACE FUNCTION public.fhorarios_disponibles(pid_especialidad integer, pfech_cita date DEFAULT CURRENT_DATE)
 RETURNS TABLE(id_especialidad integer, especialidad text, id_medico integer, medico text, nmp text,
               id_horario integer, dia_semana text, turno text, hora_inicio time without time zone,
               hora_fin time without time zone, fichas_disponibles integer)
 LANGUAGE plpgsql
AS $function$
BEGIN
    RETURN QUERY
    SELECT e.id_especialidad,
           e.nombre_especialidad::TEXT,
           em.id_empleado,
           (p.nombre || ' ' || p.apellidos)::TEXT,
           em.nmp::TEXT,
           h.id_horario,
           CASE h.dia_semana
               WHEN 1 THEN 'Lunes'
               WHEN 2 THEN 'Martes'
               WHEN 3 THEN 'Miercoles'
               WHEN 4 THEN 'Jueves'
               WHEN 5 THEN 'Viernes'
               WHEN 6 THEN 'Sabado'
               WHEN 7 THEN 'Domingo'
           END::TEXT,
           t.descripcion::TEXT,
           h.hora_inicio,
           h.hora_fin,
           (h.nro_fichas - (
                SELECT COUNT(*) FROM tc_tficha f
                 WHERE f.id_horario = h.id_horario
                   AND f.fech_cita  = pfech_cita
                   AND f.estado <> 'X'))::INTEGER
      FROM tc_horario h
      JOIN tp_empleados em ON em.id_empleado = h.id_empleado AND em.activo = TRUE
      JOIN tp_personas p   ON p.id_persona = em.id_persona
      JOIN tp_empleado_especialidades re ON re.id_empleado = em.id_empleado
      JOIN tp_especialidad e ON e.id_especialidad = re.id_especialidad
      JOIN tp_turno t ON t.id_turno = h.id_turno
     WHERE e.id_especialidad = pid_especialidad
       AND h.activo = TRUE
       AND h.dia_semana = EXTRACT(ISODOW FROM pfech_cita)::SMALLINT
       AND h.nro_fichas > (
            SELECT COUNT(*) FROM tc_tficha f
             WHERE f.id_horario = h.id_horario
               AND f.fech_cita  = pfech_cita
               AND f.estado <> 'X')
     ORDER BY t.id_turno, h.hora_inicio;
END;
$function$;

-- Registro y cambio de estado de fichas (RPC para PostgREST) --------------
CREATE OR REPLACE PROCEDURE public.pficha(IN oper integer, IN pid_ficha integer, IN pid_persona integer, IN pci character varying, IN pid_especialidad integer, IN pid_medico integer, IN pid_horario integer, IN pfech_cita date, IN phora_cita time without time zone, IN pestado character, IN pusuario character varying, IN pobservacion character varying, OUT resultado json)
 LANGUAGE plpgsql
AS $procedure$
DECLARE
    filas          INT;
    v_id_ficha     INT;
    v_nro_ficha    INT;
    v_tipo         CHAR(1);
    v_ci_aseg      VARCHAR(15);
    v_hora_ini     TIME;
    v_hora_fin     TIME;
    v_nro_fichas   INT;
    v_dia          SMALLINT;
    v_id_medico    INT;
    v_ocupadas     INT;
BEGIN
    IF oper = 1 THEN
        -- 1) El horario debe existir y estar activo
        SELECT h.hora_inicio, h.hora_fin, h.nro_fichas, h.dia_semana, h.id_empleado
          INTO v_hora_ini, v_hora_fin, v_nro_fichas, v_dia, v_id_medico
          FROM tc_horario h
         WHERE h.id_horario = pid_horario AND h.activo = TRUE;

        IF NOT FOUND THEN
            RAISE EXCEPTION 'El horario no existe o esta inactivo';
        END IF;

        -- 2) El horario debe pertenecer al medico indicado
        IF v_id_medico <> pid_medico THEN
            RAISE EXCEPTION 'El horario no pertenece al medico indicado';
        END IF;

        -- 3) El medico debe atender ese dia de la semana (1=Lunes..7=Domingo)
        IF v_dia <> EXTRACT(ISODOW FROM pfech_cita)::SMALLINT THEN
            RAISE EXCEPTION 'El medico no atiende el dia de la fecha solicitada';
        END IF;

        -- 4) La hora de la cita debe estar dentro del horario
        IF v_hora_ini < v_hora_fin THEN
            IF phora_cita < v_hora_ini OR phora_cita > v_hora_fin THEN
                RAISE EXCEPTION 'La hora % no esta dentro del horario % - %', phora_cita, v_hora_ini, v_hora_fin;
            END IF;
        ELSE
            -- horario que cruza la medianoche
            IF phora_cita < v_hora_ini AND phora_cita > v_hora_fin THEN
                RAISE EXCEPTION 'La hora % no esta dentro del horario nocturno % - %', phora_cita, v_hora_ini, v_hora_fin;
            END IF;
        END IF;

        -- 5) Verificar cupos disponibles para ese horario y fecha
        SELECT COUNT(*) INTO v_ocupadas
          FROM tc_ficha
         WHERE id_horario = pid_horario AND fech_cita = pfech_cita AND estado <> 'X';

        IF v_ocupadas >= v_nro_fichas THEN
            RAISE EXCEPTION 'No hay fichas disponibles para ese horario (cupo %)', v_nro_fichas;
        END IF;

        -- 6) Determinar si el paciente es asegurado (existe su CI en tasegurado)
        SELECT t.ci INTO v_ci_aseg
          FROM tp_asegurado t
         WHERE t.ci = pci AND t.estado = TRUE;

        IF v_ci_aseg IS NOT NULL THEN
            v_tipo := 'A';
        ELSE
            v_tipo := 'P';
        END IF;

        -- 7) Numero de ficha consecutivo del dia
        SELECT COALESCE(MAX(nro_ficha), 0) + 1 INTO v_nro_ficha
          FROM tc_ficha
         WHERE fech_cita = pfech_cita;

        -- 8) Insertar la ficha
        INSERT INTO tc_ficha (nro_ficha, id_persona, ci_paciente, tipo_paciente, id_asegurado,
                            id_medico, id_especialidad, id_horario, fech_cita, hora_cita,
                            estado, observacion, usuario_reg)
        VALUES (v_nro_ficha, pid_persona, pci, v_tipo, v_ci_aseg,
                pid_medico, pid_especialidad, pid_horario, pfech_cita, phora_cita,
                'R', pobservacion, pusuario)
        RETURNING id_ficha INTO v_id_ficha;

        resultado := json_build_object(
            'success',       TRUE,
            'id_ficha',      v_id_ficha,
            'nro_ficha',     v_nro_ficha,
            'tipo_paciente', v_tipo,
            'message',       'Ficha registrada correctamente'
        );

    ELSIF oper = 2 THEN
        UPDATE tc_ficha SET estado = pestado WHERE id_ficha = pid_ficha;
        GET DIAGNOSTICS filas = ROW_COUNT;

        IF filas = 0 THEN
            resultado := json_build_object('success', FALSE, 'message', 'Ficha no encontrada');
        ELSE
            resultado := json_build_object('success', TRUE, 'message', 'Estado de ficha actualizado');
        END IF;

    ELSE
        resultado := json_build_object('success', FALSE, 'message', 'Operacion no valida');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        resultado := json_build_object(
            'success', FALSE,
            'message', 'Error en la base de datos',
            'details', SQLERRM
        );
END;
$procedure$;


-- =====================================================================
-- 7. TRIGGERS
-- =====================================================================

-- Horarios: validar coherencia con el turno -------------------------------
CREATE TRIGGER trg_valida_horario
    BEFORE INSERT OR UPDATE OF hora_inicio, hora_fin, id_turno ON tc_horario
    FOR EACH ROW EXECUTE FUNCTION trg_valida_horario();

-- Horarios: solo medicos ---------------------------------------------------
CREATE TRIGGER trg_horario_solo_medico
    BEFORE INSERT OR UPDATE OF id_empleado ON tc_horario
    FOR EACH ROW EXECUTE FUNCTION f_valida_empleado_medico();

-- Fichas: solo medicos ------------------------------------------------------
CREATE TRIGGER trg_ficha_solo_medico
    BEFORE INSERT OR UPDATE OF id_medico ON tc_ficha
    FOR EACH ROW EXECUTE FUNCTION f_valida_empleado_medico();


-- =====================================================================
-- 8. VISTA
-- =====================================================================

-- Fichas del dia con datos legibles (paciente, medico, servicio, estado) --
CREATE VIEW public.v_fichas_dia AS
 SELECT f.id_ficha,
        f.nro_ficha,
        f.id_persona,
        f.ci_paciente,
        f.tipo_paciente,
        CASE f.tipo_paciente
            WHEN 'A'::bpchar THEN 'Asegurado'::text
            ELSE 'Particular'::text
        END AS tipo_desc,
        CASE WHEN a.ci IS NOT NULL
             THEN ((a.nombre::text || ' ') || a.paterno::text) || ' ' || a.materno::text
             ELSE f.ci_paciente::text
        END AS paciente,
        e.nombre_especialidad AS especialidad,
        --(((mp.nombre::text || ' ') || mp.apellidos::text)) AS medico,
        s.nombre_servicio AS servicio,
        f.fech_cita,
        f.hora_cita,
        f.estado,
        CASE f.estado
            WHEN 'R'::bpchar THEN 'Registrada'::text
            WHEN 'C'::bpchar THEN 'Confirmada'::text
            WHEN 'A'::bpchar THEN 'Atendida'::text
            WHEN 'N'::bpchar THEN 'No asistio'::text
            WHEN 'X'::bpchar THEN 'Cancelada'::text
            ELSE NULL::text
        END AS estado_desc,
        f.observacion,
        f.fech_reg,
        f.usuario_reg
   FROM tc_ficha f
     JOIN tp_especialidades e ON e.id_especialidad = f.id_especialidad
     JOIN tp_empleados em ON em.id_empleado = f.id_medico
     JOIN tp_personas mp ON mp.id_persona = em.id_persona
     LEFT JOIN tc_servicios s ON s.id_servicio = f.id_servicio
     LEFT JOIN tp_asegurado a ON a.ci::text = f.id_asegurado::text;

--*************************************************************************
