\set ON_ERROR_STOP on

BEGIN;

-- Evita que dos personas apliquen simultáneamente esta migración.
SELECT pg_advisory_xact_lock(hashtext('farmacia:001_catalogo_tipos_producto'));

CREATE TABLE IF NOT EXISTS tf_tipos_producto (
    id_tipo_producto integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo varchar(30) NOT NULL,
    nombre varchar(100) NOT NULL,
    descripcion varchar(255),
    activo boolean NOT NULL DEFAULT true,
    CONSTRAINT uq_tf_tipos_producto_codigo UNIQUE (codigo),
    CONSTRAINT uq_tf_tipos_producto_nombre UNIQUE (nombre),
    CONSTRAINT ck_tf_tipos_producto_codigo_formato
        CHECK (codigo = upper(btrim(codigo)) AND codigo <> '')
);

COMMENT ON TABLE tf_tipos_producto IS
    'Catálogo administrable de tipos generales de productos de Farmacia.';
COMMENT ON COLUMN tf_tipos_producto.codigo IS
    'Código estable para integraciones; no debe usarse como texto visible.';

INSERT INTO tf_tipos_producto (codigo, nombre, descripcion)
VALUES
    ('MEDICAMENTO', 'Medicamento', 'Producto farmacéutico de uso terapéutico.'),
    ('INSUMO_MEDICO', 'Insumo médico', 'Material consumible utilizado durante la atención.'),
    ('DISPOSITIVO_MEDICO', 'Dispositivo médico', 'Instrumento o elemento médico no farmacológico.'),
    ('REACTIVO', 'Reactivo', 'Producto utilizado en procesos diagnósticos o de laboratorio.'),
    ('OTRO', 'Otro', 'Producto que no corresponde a los tipos anteriores.')
ON CONFLICT (codigo) DO NOTHING;

ALTER TABLE tf_productos
    ADD COLUMN IF NOT EXISTS id_tipo_producto integer;

-- La migración se detiene ante un texto desconocido. Nunca lo convierte a OTRO
-- silenciosamente porque eso perdería información en alguna de las siete bases.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM tf_productos p
        WHERE CASE upper(btrim(p.tipo_producto))
                  WHEN 'INSUMO' THEN 'INSUMO_MEDICO'
                  WHEN 'DISPOSITIVO' THEN 'DISPOSITIVO_MEDICO'
                  ELSE upper(btrim(p.tipo_producto))
              END NOT IN (
                  SELECT t.codigo FROM tf_tipos_producto t
              )
    ) THEN
        RAISE EXCEPTION
            'Existen valores desconocidos en tf_productos.tipo_producto. Ejecute primero la auditoría y defina su equivalencia.';
    END IF;
END $$;

UPDATE tf_productos p
SET id_tipo_producto = t.id_tipo_producto
FROM tf_tipos_producto t
WHERE t.codigo = CASE upper(btrim(p.tipo_producto))
                     WHEN 'INSUMO' THEN 'INSUMO_MEDICO'
                     WHEN 'DISPOSITIVO' THEN 'DISPOSITIVO_MEDICO'
                     ELSE upper(btrim(p.tipo_producto))
                 END
  AND p.id_tipo_producto IS DISTINCT FROM t.id_tipo_producto;

-- Compatibilidad temporal: el backend actual todavía escribe tipo_producto.
-- El trigger mantiene ambas columnas relacionadas hasta que el backend migre
-- completamente a id_tipo_producto.
CREATE OR REPLACE FUNCTION tf_sincronizar_tipo_producto()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    v_codigo_texto varchar(30);
    v_codigo_id varchar(30);
    v_id_tipo integer;
BEGIN
    -- Compatibilidad bidireccional durante la transición:
    -- * backend antiguo cambia tipo_producto y no conoce el nuevo ID;
    -- * backend nuevo cambia id_tipo_producto y puede omitir el texto legado.
    IF TG_OP = 'UPDATE' THEN
        IF NEW.tipo_producto IS DISTINCT FROM OLD.tipo_producto
           AND NEW.id_tipo_producto IS NOT DISTINCT FROM OLD.id_tipo_producto THEN
            NEW.id_tipo_producto := NULL;
        ELSIF NEW.id_tipo_producto IS DISTINCT FROM OLD.id_tipo_producto
              AND NEW.tipo_producto IS NOT DISTINCT FROM OLD.tipo_producto THEN
            NEW.tipo_producto := NULL;
        END IF;
    END IF;

    IF NEW.tipo_producto IS NOT NULL THEN
        v_codigo_texto := CASE upper(btrim(NEW.tipo_producto))
                              WHEN 'INSUMO' THEN 'INSUMO_MEDICO'
                              WHEN 'DISPOSITIVO' THEN 'DISPOSITIVO_MEDICO'
                              ELSE upper(btrim(NEW.tipo_producto))
                          END;
    END IF;

    IF NEW.id_tipo_producto IS NULL THEN
        SELECT t.id_tipo_producto
        INTO v_id_tipo
        FROM tf_tipos_producto t
        WHERE t.codigo = v_codigo_texto;

        IF v_id_tipo IS NULL THEN
            RAISE EXCEPTION 'Tipo de producto desconocido: %', NEW.tipo_producto;
        END IF;

        NEW.id_tipo_producto := v_id_tipo;
    ELSE
        SELECT t.codigo
        INTO v_codigo_id
        FROM tf_tipos_producto t
        WHERE t.id_tipo_producto = NEW.id_tipo_producto;

        IF v_codigo_id IS NULL THEN
            RAISE EXCEPTION 'id_tipo_producto inexistente: %', NEW.id_tipo_producto;
        END IF;

        IF v_codigo_texto IS NOT NULL AND v_codigo_texto <> v_codigo_id THEN
            RAISE EXCEPTION
                'tipo_producto (%) no coincide con id_tipo_producto (%)',
                NEW.tipo_producto, NEW.id_tipo_producto;
        END IF;

        IF NEW.tipo_producto IS NULL THEN
            NEW.tipo_producto := v_codigo_id;
        END IF;
    END IF;

    RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS trg_tf_productos_sincronizar_tipo ON tf_productos;
CREATE TRIGGER trg_tf_productos_sincronizar_tipo
BEFORE INSERT OR UPDATE OF tipo_producto, id_tipo_producto
ON tf_productos
FOR EACH ROW
EXECUTE FUNCTION tf_sincronizar_tipo_producto();

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conrelid = 'tf_productos'::regclass
          AND conname = 'fk_tf_productos_tipo_producto'
    ) THEN
        ALTER TABLE tf_productos
            ADD CONSTRAINT fk_tf_productos_tipo_producto
            FOREIGN KEY (id_tipo_producto)
            REFERENCES tf_tipos_producto(id_tipo_producto)
            DEFERRABLE INITIALLY IMMEDIATE;
    END IF;
END $$;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM tf_productos WHERE id_tipo_producto IS NULL) THEN
        RAISE EXCEPTION 'No todos los productos pudieron relacionarse con un tipo.';
    END IF;
END $$;

ALTER TABLE tf_productos
    ALTER COLUMN id_tipo_producto SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_tf_productos_id_tipo_producto
    ON tf_productos(id_tipo_producto);

COMMENT ON COLUMN tf_productos.id_tipo_producto IS
    'Tipo general del producto. Relación autoritativa con tf_tipos_producto.';
COMMENT ON COLUMN tf_productos.tipo_producto IS
    'Columna legada conservada temporalmente para compatibilidad; no eliminar hasta migrar los siete backends.';

COMMIT;
