\set ON_ERROR_STOP on

-- Actualización completa de Farmacia e Inventario desde la BD original.
-- Archivo único para ejecutar con psql. Crear respaldo antes.
-- No ejecutar desde la aplicación ni sobre una BD que no sea la hospitalaria.

DO $$
BEGIN
    IF to_regclass('public.tf_productos') IS NULL OR to_regclass('public.tf_lotes') IS NULL OR to_regclass('public.tf_dispensaciones') IS NULL OR to_regclass('public.tf_detalles_dispensacion') IS NULL OR to_regclass('public.tf_consumos_internos') IS NULL OR to_regclass('public.tf_detalles_consumo') IS NULL OR to_regclass('public.tf_movimientos_inventario') IS NULL THEN
        RAISE EXCEPTION 'No corresponde a la BD original de Farmacia. No se modificó nada.';
    END IF;
END $$;

-- ===== 001: catálogo y tipos de producto =====
\set ON_ERROR_STOP on

BEGIN;

-- Evita que dos personas apliquen simultáneamente esta migración.
SELECT pg_advisory_xact_lock(hashtext('farmacia:001_catalogo_tipos_producto'));

CREATE TABLE IF NOT EXISTS tf_tipos_producto (
    id_tipo_producto integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo varchar(30) NOT NULL,
    nombre varchar(100) NOT NULL,
    descripcion varchar(255),
    activo boolean NOT NULL DEFAULT true,
    CONSTRAINT uq_tf_tipos_producto_codigo UNIQUE (codigo),
    CONSTRAINT uq_tf_tipos_producto_nombre UNIQUE (nombre),
    CONSTRAINT ck_tf_tipos_producto_codigo_formato
        CHECK (codigo = upper(btrim(codigo)) AND codigo <> '')
);

COMMENT ON TABLE tf_tipos_producto IS
    'Catálogo administrable de tipos generales de productos de Farmacia.';
COMMENT ON COLUMN tf_tipos_producto.codigo IS
    'Código estable para integraciones; no debe usarse como texto visible.';

INSERT INTO tf_tipos_producto (codigo, nombre, descripcion)
VALUES
    ('MEDICAMENTO', 'Medicamento', 'Producto farmacéutico de uso terapéutico.'),
    ('INSUMO_MEDICO', 'Insumo médico', 'Material consumible utilizado durante la atención.'),
    ('DISPOSITIVO_MEDICO', 'Dispositivo médico', 'Instrumento o elemento médico no farmacológico.'),
    ('REACTIVO', 'Reactivo', 'Producto utilizado en procesos diagnósticos o de laboratorio.'),
    ('OTRO', 'Otro', 'Producto que no corresponde a los tipos anteriores.')
ON CONFLICT (codigo) DO NOTHING;

ALTER TABLE tf_productos
    ADD COLUMN IF NOT EXISTS id_tipo_producto integer;

-- La migración se detiene ante un texto desconocido. Nunca lo convierte a OTRO
-- silenciosamente porque eso perdería información en alguna de las siete bases.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM tf_productos p
        WHERE CASE upper(btrim(p.tipo_producto))
                  WHEN 'INSUMO' THEN 'INSUMO_MEDICO'
                  WHEN 'DISPOSITIVO' THEN 'DISPOSITIVO_MEDICO'
                  ELSE upper(btrim(p.tipo_producto))
              END NOT IN (
                  SELECT t.codigo FROM tf_tipos_producto t
              )
    ) THEN
        RAISE EXCEPTION
            'Existen valores desconocidos en tf_productos.tipo_producto. Ejecute primero la auditoría y defina su equivalencia.';
    END IF;
END $$;

UPDATE tf_productos p
SET id_tipo_producto = t.id_tipo_producto
FROM tf_tipos_producto t
WHERE t.codigo = CASE upper(btrim(p.tipo_producto))
                     WHEN 'INSUMO' THEN 'INSUMO_MEDICO'
                     WHEN 'DISPOSITIVO' THEN 'DISPOSITIVO_MEDICO'
                     ELSE upper(btrim(p.tipo_producto))
                 END
  AND p.id_tipo_producto IS DISTINCT FROM t.id_tipo_producto;

-- Compatibilidad temporal: el backend actual todavía escribe tipo_producto.
-- El trigger mantiene ambas columnas relacionadas hasta que el backend migre
-- completamente a id_tipo_producto.
CREATE OR REPLACE FUNCTION tf_sincronizar_tipo_producto()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    v_codigo_texto varchar(30);
    v_codigo_id varchar(30);
    v_id_tipo integer;
BEGIN
    -- Compatibilidad bidireccional durante la transición:
    -- * backend antiguo cambia tipo_producto y no conoce el nuevo ID;
    -- * backend nuevo cambia id_tipo_producto y puede omitir el texto legado.
    IF TG_OP = 'UPDATE' THEN
        IF NEW.tipo_producto IS DISTINCT FROM OLD.tipo_producto
           AND NEW.id_tipo_producto IS NOT DISTINCT FROM OLD.id_tipo_producto THEN
            NEW.id_tipo_producto := NULL;
        ELSIF NEW.id_tipo_producto IS DISTINCT FROM OLD.id_tipo_producto
              AND NEW.tipo_producto IS NOT DISTINCT FROM OLD.tipo_producto THEN
            NEW.tipo_producto := NULL;
        END IF;
    END IF;

    IF NEW.tipo_producto IS NOT NULL THEN
        v_codigo_texto := CASE upper(btrim(NEW.tipo_producto))
                              WHEN 'INSUMO' THEN 'INSUMO_MEDICO'
                              WHEN 'DISPOSITIVO' THEN 'DISPOSITIVO_MEDICO'
                              ELSE upper(btrim(NEW.tipo_producto))
                          END;
    END IF;

    IF NEW.id_tipo_producto IS NULL THEN
        SELECT t.id_tipo_producto
        INTO v_id_tipo
        FROM tf_tipos_producto t
        WHERE t.codigo = v_codigo_texto;

        IF v_id_tipo IS NULL THEN
            RAISE EXCEPTION 'Tipo de producto desconocido: %', NEW.tipo_producto;
        END IF;

        NEW.id_tipo_producto := v_id_tipo;
    ELSE
        SELECT t.codigo
        INTO v_codigo_id
        FROM tf_tipos_producto t
        WHERE t.id_tipo_producto = NEW.id_tipo_producto;

        IF v_codigo_id IS NULL THEN
            RAISE EXCEPTION 'id_tipo_producto inexistente: %', NEW.id_tipo_producto;
        END IF;

        IF v_codigo_texto IS NOT NULL AND v_codigo_texto <> v_codigo_id THEN
            RAISE EXCEPTION
                'tipo_producto (%) no coincide con id_tipo_producto (%)',
                NEW.tipo_producto, NEW.id_tipo_producto;
        END IF;

        IF NEW.tipo_producto IS NULL THEN
            NEW.tipo_producto := v_codigo_id;
        END IF;
    END IF;

    RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS trg_tf_productos_sincronizar_tipo ON tf_productos;
CREATE TRIGGER trg_tf_productos_sincronizar_tipo
BEFORE INSERT OR UPDATE OF tipo_producto, id_tipo_producto
ON tf_productos
FOR EACH ROW
EXECUTE FUNCTION tf_sincronizar_tipo_producto();

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conrelid = 'tf_productos'::regclass
          AND conname = 'fk_tf_productos_tipo_producto'
    ) THEN
        ALTER TABLE tf_productos
            ADD CONSTRAINT fk_tf_productos_tipo_producto
            FOREIGN KEY (id_tipo_producto)
            REFERENCES tf_tipos_producto(id_tipo_producto)
            DEFERRABLE INITIALLY IMMEDIATE;
    END IF;
END $$;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM tf_productos WHERE id_tipo_producto IS NULL) THEN
        RAISE EXCEPTION 'No todos los productos pudieron relacionarse con un tipo.';
    END IF;
END $$;

ALTER TABLE tf_productos
    ALTER COLUMN id_tipo_producto SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_tf_productos_id_tipo_producto
    ON tf_productos(id_tipo_producto);

COMMENT ON COLUMN tf_productos.id_tipo_producto IS
    'Tipo general del producto. Relación autoritativa con tf_tipos_producto.';
COMMENT ON COLUMN tf_productos.tipo_producto IS
    'Columna legada conservada temporalmente para compatibilidad; no eliminar hasta migrar los siete backends.';

COMMIT;
\set ON_ERROR_STOP on

BEGIN;

SELECT pg_advisory_xact_lock(hashtext('farmacia:002_operaciones_pendientes'));

-- PENDIENTE no descuenta existencias. La confirmación transaccional del backend
-- cambia al estado final y genera la salida de inventario.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'tf_dispensaciones'::regclass
          AND conname = 'ck_tf_dispensaciones_estado'
    ) THEN
        ALTER TABLE tf_dispensaciones
            ADD CONSTRAINT ck_tf_dispensaciones_estado
            CHECK (estado IN ('PENDIENTE', 'ENTREGADA', 'ANULADA')) NOT VALID;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'tf_consumos_internos'::regclass
          AND conname = 'ck_tf_consumos_internos_estado'
    ) THEN
        ALTER TABLE tf_consumos_internos
            ADD CONSTRAINT ck_tf_consumos_internos_estado
            CHECK (estado IN ('PENDIENTE', 'REGISTRADO', 'ANULADO')) NOT VALID;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'tf_detalles_dispensacion'::regclass
          AND conname = 'ck_tf_detalles_dispensacion_cantidad'
    ) THEN
        ALTER TABLE tf_detalles_dispensacion
            ADD CONSTRAINT ck_tf_detalles_dispensacion_cantidad
            CHECK (cantidad_entregada > 0) NOT VALID;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'tf_detalles_consumo'::regclass
          AND conname = 'ck_tf_detalles_consumo_cantidad'
    ) THEN
        ALTER TABLE tf_detalles_consumo
            ADD CONSTRAINT ck_tf_detalles_consumo_cantidad
            CHECK (cantidad_entregada > 0) NOT VALID;
    END IF;
END $$;

COMMIT;

-- ===== Tabla clínica mínima requerida por el consumo conectado =====
-- Se crea solo si no existe; la definición oficial puede reemplazarla.
CREATE TABLE IF NOT EXISTS ti_detalle_prescripciones (
    id_detalle_prescripcion BIGSERIAL PRIMARY KEY,
    id_prescripcion BIGINT NOT NULL REFERENCES ti_prescripciones(id_prescripcion),
    id_producto INTEGER NOT NULL REFERENCES tf_productos(id_producto),
    cantidad_prescrita NUMERIC(12,2) NOT NULL CHECK (cantidad_prescrita > 0),
    observacion TEXT
);
CREATE INDEX IF NOT EXISTS idx_ti_detalle_prescripciones_prescripcion ON ti_detalle_prescripciones(id_prescripcion);
CREATE INDEX IF NOT EXISTS idx_ti_detalle_prescripciones_producto ON ti_detalle_prescripciones(id_producto);

-- ===== 003: consumo conectado a prescripciones =====
\set ON_ERROR_STOP on

-- Tabla mínima para pruebas de integración con Internación.
-- En producción debe conservarse la definición oficial del módulo clínico.
CREATE TABLE IF NOT EXISTS ti_detalle_prescripciones (
    id_detalle_prescripcion BIGSERIAL PRIMARY KEY,
    id_prescripcion BIGINT NOT NULL,
    id_producto INTEGER NOT NULL,
    cantidad_prescrita NUMERIC(12,2) NOT NULL,
    observacion TEXT,
    CONSTRAINT ck_ti_detalle_prescripciones_cantidad
        CHECK (cantidad_prescrita > 0),
    CONSTRAINT fk_ti_detalle_prescripcion_prescripcion
        FOREIGN KEY (id_prescripcion)
        REFERENCES ti_prescripciones(id_prescripcion),
    CONSTRAINT fk_ti_detalle_prescripcion_producto
        FOREIGN KEY (id_producto)
        REFERENCES tf_productos(id_producto)
);

CREATE INDEX IF NOT EXISTS idx_ti_detalle_prescripciones_prescripcion
    ON ti_detalle_prescripciones(id_prescripcion);

CREATE INDEX IF NOT EXISTS idx_ti_detalle_prescripciones_producto
    ON ti_detalle_prescripciones(id_producto);

BEGIN;

-- Conecta Consumo interno con las prescripciones del módulo de Internación.
-- Esta migración es aditiva: conserva las referencias antiguas a solicitudes
-- para no perder trazabilidad de datos ya registrados.
SELECT pg_advisory_xact_lock(hashtext('farmacia:003_consumo_prescripciones'));

-- La tabla de detalle pertenece al módulo clínico. No se crea aquí ni se
-- inventa su estructura; la base debe traerla desde la versión clínica
-- correspondiente.
DO $$
BEGIN
    IF to_regclass('ti_prescripciones') IS NULL THEN
        RAISE EXCEPTION
            'Falta la tabla ti_prescripciones. Instale primero la versión clínica requerida.';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'ti_prescripciones'
          AND column_name = 'id_prescripcion'
    ) THEN
        RAISE EXCEPTION
            'ti_prescripciones no contiene la columna id_prescripcion.';
    END IF;

    IF to_regclass('ti_detalle_prescripciones') IS NULL THEN
        RAISE EXCEPTION
            'Falta la tabla ti_detalle_prescripciones. Instale primero la versión clínica requerida.';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'ti_detalle_prescripciones'
          AND column_name = 'id_detalle_prescripcion'
    ) THEN
        RAISE EXCEPTION
            'ti_detalle_prescripciones no contiene la columna id_detalle_prescripcion.';
    END IF;
END $$;

ALTER TABLE tf_consumos_internos
    ADD COLUMN IF NOT EXISTS id_prescripcion bigint;

ALTER TABLE tf_detalles_consumo
    ADD COLUMN IF NOT EXISTS id_detalle_prescripcion bigint;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'tf_consumos_internos'::regclass
          AND conname = 'fk_tf_consumos_prescripcion'
    ) THEN
        ALTER TABLE tf_consumos_internos
            ADD CONSTRAINT fk_tf_consumos_prescripcion
            FOREIGN KEY (id_prescripcion)
            REFERENCES ti_prescripciones(id_prescripcion)
            DEFERRABLE INITIALLY IMMEDIATE;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'tf_detalles_consumo'::regclass
          AND conname = 'fk_tf_detalles_consumo_detalle_prescripcion'
    ) THEN
        ALTER TABLE tf_detalles_consumo
            ADD CONSTRAINT fk_tf_detalles_consumo_detalle_prescripcion
            FOREIGN KEY (id_detalle_prescripcion)
            REFERENCES ti_detalle_prescripciones(id_detalle_prescripcion)
            DEFERRABLE INITIALLY IMMEDIATE;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_tf_consumos_internos_id_prescripcion
    ON tf_consumos_internos(id_prescripcion);

CREATE INDEX IF NOT EXISTS idx_tf_detalles_consumo_id_detalle_prescripcion
    ON tf_detalles_consumo(id_detalle_prescripcion);

COMMENT ON COLUMN tf_consumos_internos.id_prescripcion IS
    'Prescripción clínica relacionada; nullable para conservar consumos históricos.';

COMMENT ON COLUMN tf_detalles_consumo.id_detalle_prescripcion IS
    'Detalle de prescripción clínica atendido; nullable para conservar consumos históricos.';

COMMIT;
\set ON_ERROR_STOP on

BEGIN;

SELECT pg_advisory_xact_lock(hashtext('farmacia:005_permitir_origen_alternativo_consumo'));

-- Ahora que tf_consumos_internos puede originarse desde id_solicitud_insumo
-- (flujo antiguo) O id_prescripcion (flujo conectado a Internación, migración 003),
-- ninguna de las dos puede ser NOT NULL individualmente. Se agrega un CHECK
-- que exige al menos una de las dos, replicando la validación ya aplicada
-- en el backend (entidades/farmacia_consumo.py).

ALTER TABLE tf_consumos_internos
    ALTER COLUMN id_solicitud_insumo DROP NOT NULL;

ALTER TABLE tf_detalles_consumo
    ALTER COLUMN id_detalle_solicitud_consumo DROP NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'tf_consumos_internos'::regclass
          AND conname = 'ck_tf_consumos_internos_origen'
    ) THEN
        ALTER TABLE tf_consumos_internos
            ADD CONSTRAINT ck_tf_consumos_internos_origen
            CHECK (id_solicitud_insumo IS NOT NULL OR id_prescripcion IS NOT NULL)
            NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'tf_detalles_consumo'::regclass
          AND conname = 'ck_tf_detalles_consumo_origen'
    ) THEN
        ALTER TABLE tf_detalles_consumo
            ADD CONSTRAINT ck_tf_detalles_consumo_origen
            CHECK (id_detalle_solicitud_consumo IS NOT NULL OR id_detalle_prescripcion IS NOT NULL)
            NOT VALID;
    END IF;
END $$;

COMMENT ON COLUMN tf_consumos_internos.id_solicitud_insumo IS
    'Origen legado del consumo. Nullable: puede venir por id_prescripcion en su lugar.';
COMMENT ON COLUMN tf_consumos_internos.id_prescripcion IS
    'Origen desde Internación (ti_prescripciones). Nullable: puede venir por id_solicitud_insumo.';

COMMIT;
\set ON_ERROR_STOP on

BEGIN;

SELECT pg_advisory_xact_lock(hashtext('farmacia:006_dispensacion_integrada'));

DO $$
BEGIN
    IF to_regclass('public.tf_productos') IS NULL
       OR to_regclass('public.tf_lotes') IS NULL
       OR to_regclass('public.tf_dispensaciones') IS NULL
       OR to_regclass('public.tf_detalles_dispensacion') IS NULL THEN
        RAISE EXCEPTION 'Faltan tablas base de Farmacia. Ejecute primero las migraciones anteriores.';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM tf_dispensaciones
        WHERE id_factura IS NOT NULL
        GROUP BY id_factura
        HAVING count(*) > 1
    ) THEN
        RAISE EXCEPTION 'Hay facturas asociadas a más de una dispensación. Revise la auditoría previa antes de continuar.';
    END IF;
END $$;

-- Precio vigente. Los detalles guardan una copia histórica y nunca recalculan
-- una orden ya pagada a partir de este valor.
ALTER TABLE tf_productos
    ADD COLUMN IF NOT EXISTS precio_venta numeric(12,2) NOT NULL DEFAULT 0;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'tf_productos'::regclass
          AND conname = 'ck_tf_productos_precio_venta'
    ) THEN
        ALTER TABLE tf_productos
            ADD CONSTRAINT ck_tf_productos_precio_venta
            CHECK (precio_venta >= 0) NOT VALID;
    END IF;
END $$;

ALTER TABLE tf_productos VALIDATE CONSTRAINT ck_tf_productos_precio_venta;

-- La misma tabla representa la nota/proforma y, después del pago, la entrega.
ALTER TABLE tf_dispensaciones
    ADD COLUMN IF NOT EXISTS origen varchar(20) NOT NULL DEFAULT 'RECETA',
    ADD COLUMN IF NOT EXISTS numero_receta_externa varchar(80),
    ADD COLUMN IF NOT EXISTS id_receta_externa bigint,
    ADD COLUMN IF NOT EXISTS version_receta integer,
    ADD COLUMN IF NOT EXISTS id_paciente_externo varchar(80),
    ADD COLUMN IF NOT EXISTS version integer NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS total numeric(14,2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS reserva_hasta timestamptz,
    ADD COLUMN IF NOT EXISTS fecha_creacion timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS fecha_actualizacion timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS fecha_pago timestamptz,
    ADD COLUMN IF NOT EXISTS motivo_anulacion varchar(255);

-- Atención confirmó que su identificador canónico es alfanumérico, por ejemplo
-- PAC-2026-00101. También convierte clones donde una versión preliminar de 006
-- hubiera creado esta columna como bigint.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'tf_dispensaciones'
          AND column_name = 'id_paciente_externo'
          AND data_type <> 'character varying'
    ) THEN
        ALTER TABLE tf_dispensaciones
            ALTER COLUMN id_paciente_externo TYPE varchar(80)
            USING id_paciente_externo::text;
    END IF;
END $$;

-- Compatibilidad con respaldos que sí conservaron receta/factura y con otros
-- que ya aplicaron la migración 004. No se elimina ninguna columna histórica.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'tf_dispensaciones'
          AND column_name = 'id_receta'
    ) THEN
        ALTER TABLE tf_dispensaciones ALTER COLUMN id_receta DROP NOT NULL;
    END IF;
    ALTER TABLE tf_dispensaciones ALTER COLUMN id_factura DROP NOT NULL;
END $$;

UPDATE tf_dispensaciones
SET fecha_creacion = COALESCE(fecha_creacion, fecha_dispensacion::timestamp),
    fecha_actualizacion = COALESCE(fecha_actualizacion, fecha_dispensacion::timestamp),
    version = GREATEST(COALESCE(version, 1), 1),
    total = COALESCE(total, 0);

ALTER TABLE tf_dispensaciones DROP CONSTRAINT IF EXISTS ck_tf_dispensaciones_estado;
ALTER TABLE tf_dispensaciones DROP CONSTRAINT IF EXISTS ck_tf_dispensaciones_origen;
ALTER TABLE tf_dispensaciones
    ADD CONSTRAINT ck_tf_dispensaciones_origen
    CHECK (origen IN ('RECETA', 'VENTA_DIRECTA')) NOT VALID;
ALTER TABLE tf_dispensaciones
    ADD CONSTRAINT ck_tf_dispensaciones_estado
    CHECK (estado IN (
        'PENDIENTE',              -- legado; no crear nuevas filas con este estado
        'PENDIENTE_PAGO',
        'PAGADA',
        'ENTREGADA',
        'VENCIDA',
        'ANULACION_SOLICITADA',
        'ANULADA'
    )) NOT VALID;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'tf_dispensaciones'::regclass
          AND conname = 'ck_tf_dispensaciones_version'
    ) THEN
        ALTER TABLE tf_dispensaciones
            ADD CONSTRAINT ck_tf_dispensaciones_version CHECK (version > 0) NOT VALID;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'tf_dispensaciones'::regclass
          AND conname = 'ck_tf_dispensaciones_total'
    ) THEN
        ALTER TABLE tf_dispensaciones
            ADD CONSTRAINT ck_tf_dispensaciones_total CHECK (total >= 0) NOT VALID;
    END IF;
END $$;

ALTER TABLE tf_dispensaciones VALIDATE CONSTRAINT ck_tf_dispensaciones_estado;
ALTER TABLE tf_dispensaciones VALIDATE CONSTRAINT ck_tf_dispensaciones_origen;
ALTER TABLE tf_dispensaciones VALIDATE CONSTRAINT ck_tf_dispensaciones_version;
ALTER TABLE tf_dispensaciones VALIDATE CONSTRAINT ck_tf_dispensaciones_total;

CREATE UNIQUE INDEX IF NOT EXISTS uq_tf_dispensaciones_id_factura
    ON tf_dispensaciones (id_factura)
    WHERE id_factura IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_tf_dispensaciones_receta_externa
    ON tf_dispensaciones (id_receta_externa, estado);
CREATE INDEX IF NOT EXISTS idx_tf_dispensaciones_numero_receta
    ON tf_dispensaciones (numero_receta_externa, estado);
CREATE INDEX IF NOT EXISTS idx_tf_dispensaciones_reserva
    ON tf_dispensaciones (estado, reserva_hasta);

ALTER TABLE tf_detalles_dispensacion
    ADD COLUMN IF NOT EXISTS id_prescripcion_externa bigint,
    ADD COLUMN IF NOT EXISTS id_producto integer,
    ADD COLUMN IF NOT EXISTS cantidad_prescrita numeric(14,2),
    ADD COLUMN IF NOT EXISTS cantidad_solicitada numeric(14,2),
    ADD COLUMN IF NOT EXISTS precio_unitario numeric(12,2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS subtotal numeric(14,2),
    ADD COLUMN IF NOT EXISTS dosis_instrucciones text;

-- Convierte filas históricas sin inventar referencias externas. El producto
-- se obtiene del lote ya validado por la FK existente.
UPDATE tf_detalles_dispensacion d
SET id_producto = COALESCE(d.id_producto, l.id_producto),
    cantidad_solicitada = COALESCE(d.cantidad_solicitada, d.cantidad_entregada),
    cantidad_prescrita = COALESCE(d.cantidad_prescrita, d.cantidad_entregada),
    precio_unitario = COALESCE(d.precio_unitario, 0),
    subtotal = COALESCE(
        d.subtotal,
        round(COALESCE(d.cantidad_solicitada, d.cantidad_entregada, 0)
              * COALESCE(d.precio_unitario, 0), 2)
    )
FROM tf_lotes l
WHERE d.id_lote = l.id_lote;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM tf_detalles_dispensacion
        WHERE id_producto IS NULL OR cantidad_solicitada IS NULL OR cantidad_prescrita IS NULL
    ) THEN
        RAISE EXCEPTION 'No fue posible completar producto/cantidades de detalles históricos. Revise lotes huérfanos.';
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'tf_detalles_dispensacion'
          AND column_name = 'id_detalle_receta'
    ) THEN
        ALTER TABLE tf_detalles_dispensacion ALTER COLUMN id_detalle_receta DROP NOT NULL;
    END IF;
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'tf_detalles_dispensacion'
          AND column_name = 'id_detalle_comprobante'
    ) THEN
        ALTER TABLE tf_detalles_dispensacion ALTER COLUMN id_detalle_comprobante DROP NOT NULL;
    END IF;
END $$;

ALTER TABLE tf_detalles_dispensacion
    ALTER COLUMN id_lote DROP NOT NULL,
    ALTER COLUMN cantidad_entregada DROP NOT NULL,
    ALTER COLUMN id_producto SET NOT NULL,
    ALTER COLUMN cantidad_prescrita SET NOT NULL,
    ALTER COLUMN cantidad_solicitada SET NOT NULL,
    ALTER COLUMN subtotal SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'tf_detalles_dispensacion'::regclass
          AND conname = 'fk_tf_detalles_dispensacion_producto'
    ) THEN
        ALTER TABLE tf_detalles_dispensacion
            ADD CONSTRAINT fk_tf_detalles_dispensacion_producto
            FOREIGN KEY (id_producto) REFERENCES tf_productos(id_producto)
            DEFERRABLE INITIALLY IMMEDIATE NOT VALID;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'tf_detalles_dispensacion'::regclass
          AND conname = 'ck_tf_detalles_dispensacion_prescrita'
    ) THEN
        ALTER TABLE tf_detalles_dispensacion
            ADD CONSTRAINT ck_tf_detalles_dispensacion_prescrita
            CHECK (cantidad_prescrita > 0) NOT VALID;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'tf_detalles_dispensacion'::regclass
          AND conname = 'ck_tf_detalles_dispensacion_solicitada'
    ) THEN
        ALTER TABLE tf_detalles_dispensacion
            ADD CONSTRAINT ck_tf_detalles_dispensacion_solicitada
            CHECK (cantidad_solicitada > 0 AND cantidad_solicitada <= cantidad_prescrita) NOT VALID;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'tf_detalles_dispensacion'::regclass
          AND conname = 'ck_tf_detalles_dispensacion_precio'
    ) THEN
        ALTER TABLE tf_detalles_dispensacion
            ADD CONSTRAINT ck_tf_detalles_dispensacion_precio
            CHECK (precio_unitario >= 0) NOT VALID;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'tf_detalles_dispensacion'::regclass
          AND conname = 'ck_tf_detalles_dispensacion_subtotal'
    ) THEN
        ALTER TABLE tf_detalles_dispensacion
            ADD CONSTRAINT ck_tf_detalles_dispensacion_subtotal
            CHECK (subtotal = round(cantidad_solicitada * precio_unitario, 2)) NOT VALID;
    END IF;
END $$;

ALTER TABLE tf_detalles_dispensacion VALIDATE CONSTRAINT fk_tf_detalles_dispensacion_producto;
ALTER TABLE tf_detalles_dispensacion VALIDATE CONSTRAINT ck_tf_detalles_dispensacion_prescrita;
ALTER TABLE tf_detalles_dispensacion VALIDATE CONSTRAINT ck_tf_detalles_dispensacion_solicitada;
ALTER TABLE tf_detalles_dispensacion VALIDATE CONSTRAINT ck_tf_detalles_dispensacion_precio;
ALTER TABLE tf_detalles_dispensacion VALIDATE CONSTRAINT ck_tf_detalles_dispensacion_subtotal;

CREATE UNIQUE INDEX IF NOT EXISTS uq_tf_detalles_dispensacion_prescripcion
    ON tf_detalles_dispensacion (id_dispensacion, id_prescripcion_externa)
    WHERE id_prescripcion_externa IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_tf_detalles_dispensacion_producto
    ON tf_detalles_dispensacion (id_producto);
CREATE INDEX IF NOT EXISTS idx_tf_detalles_dispensacion_prescripcion
    ON tf_detalles_dispensacion (id_prescripcion_externa);

CREATE TABLE IF NOT EXISTS tf_reservas_dispensacion (
    id_reserva integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_detalle_dispensacion integer NOT NULL,
    id_lote integer NOT NULL,
    cantidad numeric(14,2) NOT NULL,
    estado varchar(20) NOT NULL DEFAULT 'ACTIVA',
    fecha_reserva timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_liberacion timestamptz,
    CONSTRAINT fk_tf_reservas_detalle
        FOREIGN KEY (id_detalle_dispensacion)
        REFERENCES tf_detalles_dispensacion(id_detalle_dispensacion)
        ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT fk_tf_reservas_lote
        FOREIGN KEY (id_lote) REFERENCES tf_lotes(id_lote)
        ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT ck_tf_reservas_cantidad CHECK (cantidad > 0),
    CONSTRAINT ck_tf_reservas_estado CHECK (estado IN ('ACTIVA', 'CONSUMIDA', 'LIBERADA')),
    CONSTRAINT ck_tf_reservas_liberacion CHECK (
        (estado = 'ACTIVA' AND fecha_liberacion IS NULL)
        OR (estado IN ('CONSUMIDA', 'LIBERADA') AND fecha_liberacion IS NOT NULL)
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tf_reservas_dispensacion_activa
    ON tf_reservas_dispensacion (id_detalle_dispensacion, id_lote)
    WHERE estado = 'ACTIVA';
CREATE INDEX IF NOT EXISTS idx_tf_reservas_lote_estado
    ON tf_reservas_dispensacion (id_lote, estado);
CREATE INDEX IF NOT EXISTS idx_tf_reservas_detalle
    ON tf_reservas_dispensacion (id_detalle_dispensacion);

CREATE OR REPLACE FUNCTION farmacia_validar_reserva_producto()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM tf_detalles_dispensacion dd
        JOIN tf_lotes l ON l.id_lote = NEW.id_lote
        WHERE dd.id_detalle_dispensacion = NEW.id_detalle_dispensacion
          AND dd.id_producto = l.id_producto
    ) THEN
        RAISE EXCEPTION 'El lote % no pertenece al producto del detalle %',
            NEW.id_lote, NEW.id_detalle_dispensacion;
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_tf_reservas_validar_producto ON tf_reservas_dispensacion;
CREATE TRIGGER trg_tf_reservas_validar_producto
BEFORE INSERT OR UPDATE OF id_detalle_dispensacion, id_lote
ON tf_reservas_dispensacion
FOR EACH ROW EXECUTE FUNCTION farmacia_validar_reserva_producto();

-- La base protege el total incluso si un proceso distinto al backend actualiza
-- los detalles. La aplicación sigue calculándolo para responder inmediatamente.
CREATE OR REPLACE FUNCTION farmacia_recalcular_total_dispensacion()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    v_id integer;
BEGIN
    v_id := COALESCE(NEW.id_dispensacion, OLD.id_dispensacion);
    UPDATE tf_dispensaciones
    SET total = COALESCE((
            SELECT round(sum(subtotal), 2)
            FROM tf_detalles_dispensacion
            WHERE id_dispensacion = v_id
        ), 0),
        fecha_actualizacion = CURRENT_TIMESTAMP
    WHERE id_dispensacion = v_id;
    RETURN COALESCE(NEW, OLD);
END;
$$;

DROP TRIGGER IF EXISTS trg_tf_detalles_recalcular_total ON tf_detalles_dispensacion;
CREATE TRIGGER trg_tf_detalles_recalcular_total
AFTER INSERT OR UPDATE OF cantidad_solicitada, precio_unitario, subtotal OR DELETE
ON tf_detalles_dispensacion
FOR EACH ROW EXECUTE FUNCTION farmacia_recalcular_total_dispensacion();

UPDATE tf_dispensaciones d
SET total = COALESCE((
        SELECT round(sum(dd.subtotal), 2)
        FROM tf_detalles_dispensacion dd
        WHERE dd.id_dispensacion = d.id_dispensacion
    ), 0),
    fecha_actualizacion = CURRENT_TIMESTAMP;

COMMENT ON COLUMN tf_productos.precio_venta IS
    'Precio vigente; se copia al detalle al crear/corregir una nota pendiente.';
COMMENT ON TABLE tf_dispensaciones IS
    'Nota de dispensación central: proforma, pago y entrega. Factura/comprobante 1:1.';
COMMENT ON TABLE tf_reservas_dispensacion IS
    'Stock comprometido por lote sin modificar stock_actual hasta la entrega.';

COMMIT;

DO $$
BEGIN
    IF to_regclass('public.tf_reservas_dispensacion') IS NULL THEN
        RAISE EXCEPTION 'No se creó tf_reservas_dispensacion; revisar la salida anterior.';
    END IF;
    RAISE NOTICE 'Farmacia actualizada completamente desde BD original.';
END $$;
